# Catalogue spec, part B — vet, equipment, machinery, fertilizer, feed, fruits, produce, processing
SPEC_B = {
'vet': {
 'Vaccines': [
  ("Newcastle Disease Vaccine (LaSota, 1,000 doses)", "/vial", 3800, 5, "24 hrs (cold chain)", "Live LaSota vaccine for drinking-water administration; shipped in ice packs with cold-chain log.", {"Doses":"1,000","Route":"Drinking water / eye drop","Storage":"2–8 °C"}, [("", 3800), ("— Komorov", 4200), ("— 200 doses", 1400)]),
  ("Gumboro (IBD) Vaccine (1,000 doses)", "/vial", 4500, 5, "24 hrs (cold chain)", "Intermediate-strain IBD vaccine for broilers and pullets.", {"Doses":"1,000","Storage":"2–8 °C"}, None),
  ("Fowl Pox Vaccine (500 doses)", "/vial", 3200, 5, "24 hrs (cold chain)", "Wing-web fowl pox vaccine with applicator needles.", {"Doses":"500","Route":"Wing web"}, None),
  ("PPR Vaccine — Goats & Sheep (100 doses)", "/vial", 12500, 2, "24 hrs (cold chain)", "Peste des petits ruminants vaccine from NVRI Vom, with diluent.", {"Doses":"100","Source":"NVRI"}, None),
  ("CBPP Vaccine — Cattle (100 doses)", "/vial", 15000, 2, "24 hrs (cold chain)", "Contagious bovine pleuropneumonia vaccine for herd protection.", {"Doses":"100"}, None),
  ("Rabies Vaccine (10 doses)", "/vial", 18000, 1, "24 hrs (cold chain)", "Inactivated rabies vaccine for dogs, cats and livestock.", {"Doses":"10"}, None),
 ],
 'Antibiotics & Dewormers': [
  ("Oxytetracycline 20 % LA Injection (100 ml)", "/vial", 6500, 3, "24 hrs", "Long-acting broad-spectrum antibiotic for cattle, sheep, goats and pigs.", {"Strength":"200 mg/ml","Volume":"100 ml","Withdrawal":"28 days meat"}, [("", 6500), ("— 50 ml", 3800)]),
  ("Albendazole 10 % Oral Suspension (1 L)", "/bottle", 8500, 2, "24 hrs", "Broad-spectrum dewormer for roundworms, tapeworms and liver fluke in ruminants.", {"Strength":"100 mg/ml","Volume":"1 L"}, None),
  ("Ivermectin 1 % Injection (50 ml)", "/vial", 7200, 3, "24 hrs", "Endectocide for internal worms, mange, lice and ticks.", {"Strength":"10 mg/ml"}, None),
  ("Poultry Anticoccidial (Amprolium 20 %, 100 g)", "/sachet", 2400, 10, "24 hrs", "Water-soluble amprolium for coccidiosis prevention and treatment in poultry.", {"Strength":"20 %","Pack":"100 g"}, [("", 2400), ("— Toltrazuril 2.5 % 1 L", 14500)]),
  ("Tylosin + Doxycycline Soluble Powder (100 g)", "/sachet", 4800, 5, "24 hrs", "Combination for CRD and respiratory infections in poultry.", {"Pack":"100 g"}, None),
  ("Piperazine Poultry Dewormer (100 g)", "/sachet", 1800, 10, "24 hrs", "Water-soluble dewormer for roundworms in chickens.", {"Pack":"100 g"}, None),
 ],
 'Supplements': [
  ("Poultry Multivitamin + Electrolytes (1 kg)", "/pack", 9500, 3, "24 hrs", "Anti-stress vitamin and electrolyte powder for heat stress, transport and vaccination periods.", {"Pack":"1 kg","Vitamins":"A, D3, E, B-complex, C"}, [("", 9500), ("— 100 g", 1500)]),
  ("Cattle Mineral Salt Lick Block (5 kg)", "/block", 4800, 6, "2 days", "Mineralised salt lick with calcium, phosphorus and trace elements.", {"Weight":"5 kg"}, None),
  ("Calcium Supplement for Layers (Oyster Shell, 50 kg)", "/bag", 12500, 2, "2 days", "Crushed oyster shell grit for strong eggshells.", {"Bag":"50 kg","Calcium":"38 %"}, None),
  ("Liquid Vitamin AD3E (1 L)", "/L", 7800, 3, "24 hrs", "Oral vitamin concentrate for fertility, growth and immunity in all livestock.", {"Volume":"1 L"}, None),
  ("Fish Vitamin Premix (1 kg)", "/pack", 8200, 3, "24 hrs", "Vitamin C-stabilised premix for catfish and tilapia feed.", {"Pack":"1 kg"}, None),
 ],
 'Diagnostics': [
  ("Post-Mortem & Lab Diagnosis (Poultry)", "/case", 15000, 1, "24 hrs", "Necropsy with bacteriology and parasitology report and treatment plan.", {"Turnaround":"24–48 hrs","Report":"PDF + call"}, None),
  ("Brucellosis / TB Herd Screening", "/animal", 4500, 10, "By schedule", "On-farm sampling and lab testing with certificates for cattle trade.", {"Tests":"RBPT, tuberculin"}, None),
  ("Fish Disease Diagnosis & Water Test", "/visit", 25000, 1, "48 hrs", "Farm visit, microscopy and water chemistry with corrective plan.", {"Includes":"Microscopy, water test"}, None),
  ("Feed & Mycotoxin Analysis", "/sample", 22000, 1, "5 days", "Proximate analysis and aflatoxin screening of feed or grain samples.", {"Parameters":"Protein, fat, fibre, aflatoxin"}, None),
 ],
 'Vet Clinics': [
  ("Farm Herd Health Visit (Cattle / Goats)", "/visit", 40000, 1, "By schedule", "Veterinary doctor visit with clinical examination, treatment and herd advice for up to 50 animals.", {"Animals":"Up to 50","Includes":"Consultation"}, None),
  ("Poultry Flock Health Audit", "/visit", 35000, 1, "By schedule", "Biosecurity review, flock inspection, vaccination schedule and litter management plan.", {"Flock":"Any size","Report":"Written"}, None),
  ("Small-Animal Surgery & Castration", "/animal", 12000, 1, "By schedule", "Castration, dehorning and minor surgery for goats, sheep and pigs.", {"Anaesthesia":"Local"}, None),
  ("Dairy Mastitis Management Programme", "/month", 60000, 1, "Monthly", "Monthly CMT testing, milking-hygiene training and treatment protocol.", {"Frequency":"Monthly"}, None),
 ],
 'Mobile Vet Services': [
  ("Mobile Vaccination Team — Poultry (per 1,000 birds)", "/1000", 18000, 1, "By schedule", "Trained team administers eye-drop, injection or wing-web vaccines on your farm with cold-chain vaccines included.", {"Includes":"Vaccine + labour"}, None),
  ("Mobile Livestock Deworming & Spraying", "/visit", 30000, 1, "By schedule", "Deworming, tick spraying and vitamin injections for up to 100 head.", {"Animals":"Up to 100"}, None),
  ("Emergency Vet Call-Out (24/7)", "/call", 25000, 1, "Within 3 hrs", "Rapid response for dystocia, bloat, poisoning and outbreaks in Lagos, Ogun and Oyo.", {"Response":"≤ 3 hrs","Coverage":"South-West"}, None),
  ("Artificial Insemination Technician Visit", "/visit", 20000, 1, "By schedule", "Certified AI technician for cattle and goats; semen priced separately.", {"Species":"Cattle, goats"}, None),
 ],
},
'equipment': {
 'Hand Tools': [
  ("Farm Tool Set (Hoe, Cutlass, Rake, Shovel, Fork)", "/set", 28500, 1, "24 hrs", "Five forged-steel tools with hardwood handles for smallholder farms.", {"Pieces":"5","Steel":"Forged carbon"}, None),
  ("West African Hoe (Forged, Pack of 10)", "/pack", 32000, 1, "24 hrs", "Heavy-duty short-handled hoes for ridging and weeding.", {"Count":"10","Blade":"Forged"}, None),
  ("Cutlass / Machete 24\" (Pack of 12)", "/pack", 36000, 1, "24 hrs", "Tempered-steel machetes for land clearing and harvesting.", {"Count":"12","Length":"24 in"}, None),
  ("Wheelbarrow (Heavy-Duty, 100 L)", "", 38000, 1, "2 days", "Steel-tray wheelbarrow with pneumatic tyre for farm haulage.", {"Capacity":"100 L","Tyre":"Pneumatic"}, None),
  ("Pruning Shears & Loppers Set", "/set", 14500, 1, "24 hrs", "Bypass secateurs, lopper and folding saw for orchards.", {"Pieces":"3"}, None),
  ("Hand Seed Planter (Jab Planter)", "", 18500, 1, "2 days", "Two-handed jab planter for maize, beans and soybean; adjustable seed plate.", {"Crops":"Maize, beans, soybean"}, None),
 ],
 'Sprayers': [
  ("Solar Rechargeable Knapsack Sprayer 16 L", "", 55000, 1, "24 hrs", "Battery sprayer with solar panel for off-grid recharging.", {"Capacity":"16 L","Charging":"Solar + mains"}, None),
  ("Trolley Power Sprayer (100 L, Petrol)", "", 285000, 1, "3 days", "Wheeled petrol sprayer with 50 m hose for orchards and greenhouses.", {"Tank":"100 L","Hose":"50 m"}, None),
  ("Hand-Held Pressure Sprayer 5 L", "", 6500, 2, "24 hrs", "Compact compression sprayer for nurseries and gardens.", {"Capacity":"5 L"}, [("", 6500), ("— 8 L", 8500)]),
  ("ULV Cold Fogger (Electric)", "", 145000, 1, "3 days", "Ultra-low-volume fogger for poultry-house disinfection and greenhouse pests.", {"Tank":"5 L","Droplet":"10–50 µm"}, None),
 ],
 'Water Pumps': [
  ("Petrol Water Pump 2\" (5.5 HP)", "", 125000, 1, "2 days", "Self-priming centrifugal pump, 30 m³/h, for irrigation and pond filling.", {"Inlet":"2 in","Flow":"30 m³/h","Engine":"5.5 HP petrol"}, [("", 125000), ("— 3 in (6.5 HP)", 165000), ("— 4 in diesel", 320000)]),
  ("Submersible Borehole Pump 1 HP", "", 95000, 1, "2 days", "Stainless multistage submersible for boreholes up to 60 m.", {"Power":"1 HP","Head":"60 m"}, [("", 95000), ("— 2 HP", 145000)]),
  ("Diesel Irrigation Pump 3\" (Kirloskar type)", "", 385000, 1, "5 days", "Heavy-duty diesel pump set with base frame for river and canal lifting.", {"Inlet":"3 in","Flow":"60 m³/h"}, None),
  ("Surface Booster Pump 1 HP", "", 48000, 1, "24 hrs", "Electric booster for drip lines and overhead tanks.", {"Power":"1 HP"}, None),
 ],
 'Incubators': [
  ("Solar-Powered Incubator (200 eggs)", "", 320000, 1, "5 days", "DC incubator with battery back-up for off-grid hatcheries.", {"Capacity":"200 eggs","Power":"12 V solar"}, None),
  ("Cabinet Incubator (1,232 eggs, Setter + Hatcher)", "", 1250000, 1, "7–10 days", "Commercial cabinet with separate hatcher, humidity pump and alarm.", {"Capacity":"1,232","Alarm":"Yes"}, None),
  ("Reptile / Quail Incubator (120 eggs)", "", 68000, 1, "3 days", "Small incubator with quail trays and auto-turn.", {"Capacity":"120 quail eggs"}, None),
  ("Incubator Thermostat & Humidity Controller", "", 18500, 1, "24 hrs", "Digital replacement controller with dual sensors.", {"Range":"0–99 °C / 0–99 % RH"}, None),
 ],
 'Milking Machines': [
  ("Portable Milking Machine (Single Bucket, 25 L)", "", 385000, 1, "5–7 days", "Electric vacuum milker for 10–20 cows per hour with stainless bucket.", {"Bucket":"25 L","Output":"10–20 cows/hr"}, [("", 385000), ("— double bucket", 560000), ("— goat / sheep", 340000)]),
  ("Milk Cooling Tank (500 L)", "", 2800000, 1, "14 days", "Direct-expansion bulk milk cooler with agitator.", {"Volume":"500 L","Cooling":"35 → 4 °C in 3 hrs"}, None),
  ("Stainless Milk Cans (40 L, Pack of 2)", "/pack", 95000, 1, "3 days", "Food-grade stainless steel milk churns with sealed lids.", {"Volume":"40 L","Count":"2"}, None),
  ("Teat Dip & Mastitis Test Kit", "/kit", 22000, 1, "24 hrs", "Iodine teat dip 5 L, dip cup and California mastitis test paddle.", {"Includes":"Dip, cup, CMT"}, None),
 ],
 'Weighing Scales': [
  ("Platform Scale 300 kg (Digital)", "", 68000, 1, "2 days", "Stainless platform scale for sacks and crates with rechargeable indicator.", {"Capacity":"300 kg","Division":"50 g"}, [("", 68000), ("— 500 kg", 85000), ("— 1,000 kg", 145000)]),
  ("Livestock Weighing Scale (2,000 kg)", "", 650000, 1, "10 days", "Cattle crate scale with load bars and digital readout.", {"Capacity":"2,000 kg","Crate":"Galvanised"}, None),
  ("Hanging Crane Scale 500 kg", "", 45000, 1, "2 days", "Digital hook scale for bags, carcasses and bunches.", {"Capacity":"500 kg"}, None),
  ("Table Top Price Scale 30 kg", "", 24000, 1, "24 hrs", "Retail scale for produce shops and market stalls.", {"Capacity":"30 kg","Division":"5 g"}, None),
 ],
 'Solar Kits': [
  ("Solar Farm Lighting Kit (4 lamps + phone charging)", "/kit", 85000, 1, "3 days", "Pay-as-you-grow solar home system for farm houses and poultry pens.", {"Panel":"50 W","Lamps":"4 LED"}, None),
  ("3 kVA Solar Inverter System (Complete)", "/system", 1850000, 1, "7 days", "3 kVA hybrid inverter, 4 × 250 W panels and 2 lithium batteries for farm offices and cold rooms.", {"Inverter":"3 kVA hybrid","Battery":"5 kWh lithium"}, [("", 1850000), ("— 5 kVA", 2950000), ("— 10 kVA", 6200000)]),
  ("Solar Electric Fence Energizer (10 km)", "", 165000, 1, "5 days", "Solar-powered energizer to secure livestock paddocks and farms.", {"Range":"10 km","Panel":"20 W"}, None),
  ("Solar Poultry Lighting Controller & LED Kit", "/kit", 120000, 1, "5 days", "Dimmable LED layer lighting with timer for 1,000-bird houses.", {"Birds":"1,000","Timer":"Programmable"}, None),
 ],
},
'machinery': {
 'Tractors': [
  ("Tractor 75 HP 4WD (New)", "", 28500000, 1, "14–21 days", "Brand-new 75 HP four-wheel-drive tractor with cabin canopy, dual-clutch and 12-month warranty; includes operator training.", {"Power":"75 HP","Drive":"4WD","Warranty":"12 months"}, [("", 28500000), ("— 55 HP 2WD", 19500000), ("— 90 HP 4WD", 36000000), ("— 110 HP 4WD", 48000000)]),
  ("Tractor 60 HP (Refurbished, Massey Ferguson)", "", 12500000, 1, "7 days", "Fully serviced Massey Ferguson 375 with new tyres and 6-month warranty.", {"Power":"75 HP","Condition":"Refurbished","Hours":"~4,000"}, None),
  ("Mini Tractor 25 HP with Rotavator", "", 7800000, 1, "10 days", "Compact tractor for vegetable farms, greenhouses and orchards.", {"Power":"25 HP","Implement":"Rotavator included"}, None),
  ("Tractor Hire with Operator (per hectare)", "/ha", 38000, 1, "By schedule", "Ploughing, harrowing or ridging with an experienced operator; diesel included.", {"Operation":"Plough / harrow / ridge","Fuel":"Included"}, None),
 ],
 'Combine Harvesters': [
  ("Rice Combine Harvester (Track Type, 88 HP)", "", 42000000, 1, "21–30 days", "Full-feed tracked combine for wet paddy fields; 0.8 ha/hr with grain tank.", {"Power":"88 HP","Capacity":"0.8 ha/hr","Crops":"Rice, wheat, soybean"}, None),
  ("Maize Combine Header (4-Row)", "", 9500000, 1, "21 days", "Four-row corn header compatible with common wheeled combines.", {"Rows":"4","Spacing":"75 cm"}, None),
  ("Mini Combine Harvester (Walk-behind, Rice/Wheat)", "", 4800000, 1, "14 days", "Self-propelled mini combine for smallholders; cuts, threshes and bags.", {"Width":"1.2 m","Engine":"Diesel 18 HP"}, None),
  ("Combine Harvesting Service (per hectare)", "/ha", 65000, 5, "By schedule", "Contract harvesting of rice, maize or soybean with our combines and crew.", {"Crops":"Rice, maize, soybean"}, None),
 ],
 'Planters & Seeders': [
  ("Tractor-Mounted Maize Planter (2-Row)", "", 2650000, 1, "10 days", "Precision pneumatic planter with fertilizer hopper.", {"Rows":"2","Crops":"Maize, soybean, groundnut"}, [("", 2650000), ("— 4-row", 4800000)]),
  ("Rice Transplanter (Walk-behind, 4-Row)", "", 3900000, 1, "14 days", "Mat-seedling transplanter, 0.15 ha/hr, reduces labour by 80 %.", {"Rows":"4","Capacity":"0.15 ha/hr"}, None),
  ("Seed Drill (Tractor, 12-Row)", "", 3200000, 1, "14 days", "Grain drill for wheat, rice and sorghum with fertilizer box.", {"Rows":"12","Width":"2.4 m"}, None),
  ("Manual Vegetable Seeder (Push type)", "", 85000, 1, "3 days", "Single-row push seeder with interchangeable plates for onions, carrots and amaranth.", {"Rows":"1","Plates":"6"}, None),
 ],
 'Ploughs & Tillers': [
  ("Disc Plough (3-Disc, Heavy Duty)", "", 1450000, 1, "7 days", "Three-disc mounted plough for 60–80 HP tractors.", {"Discs":"3 × 26 in","Tractor":"60–80 HP"}, [("", 1450000), ("— 4-disc", 1850000)]),
  ("Disc Harrow (20-Disc, Offset)", "", 2100000, 1, "7 days", "Offset harrow for seed-bed preparation, 2 m working width.", {"Discs":"20","Width":"2 m"}, None),
  ("Rotavator (1.8 m, Gear Drive)", "", 1650000, 1, "7 days", "Heavy-duty rotary tiller for fine tilth in one pass.", {"Width":"1.8 m","Blades":"48"}, None),
  ("Ridger (3-Row, Adjustable)", "", 680000, 1, "5 days", "Mouldboard ridger for yam, cassava and vegetable beds.", {"Rows":"3","Spacing":"Adjustable"}, None),
  ("Power Tiller 12 HP (Diesel, Walk-behind)", "", 1850000, 1, "7 days", "Two-wheel tractor with rotary tiller and trailer hitch for small farms.", {"Power":"12 HP","Fuel":"Diesel"}, None),
 ],
 'Threshers': [
  ("Multi-Crop Thresher (Diesel, 1.5 t/hr)", "", 1950000, 1, "10 days", "Threshes rice, maize, soybean, sorghum and cowpea with adjustable concave.", {"Capacity":"1.5 t/hr","Engine":"12 HP diesel"}, None),
  ("Maize Sheller (Electric, 1 t/hr)", "", 385000, 1, "5 days", "Cob-in, grain-out sheller with cob separation.", {"Capacity":"1 t/hr","Motor":"3 HP"}, [("", 385000), ("— petrol 2 t/hr", 620000)]),
  ("Groundnut Sheller / Decorticator", "", 285000, 1, "5 days", "Shells groundnuts with minimal kernel breakage.", {"Capacity":"500 kg/hr"}, None),
  ("Cowpea / Soybean Thresher (Mobile)", "", 1250000, 1, "7 days", "Trailer-mounted thresher for legume harvest.", {"Capacity":"800 kg/hr"}, None),
 ],
 'Balers': [
  ("Round Hay Baler (Mini, PTO)", "", 4200000, 1, "14 days", "Compact round baler producing 50 × 70 cm bales for hay and rice straw.", {"Bale":"50 × 70 cm","Tractor":"25 HP+"}, None),
  ("Square Baler (Tractor Mounted)", "", 7800000, 1, "21 days", "Conventional small square baler with twine tie.", {"Bale":"36 × 46 cm","Capacity":"300 bales/hr"}, None),
  ("Silage Chopper (Forage Harvester, Single Row)", "", 3600000, 1, "14 days", "Chops maize or napier for silage with trailer spout.", {"Rows":"1","Output":"8 t/hr"}, None),
  ("Hay Bales (Rhodes Grass, per Bale)", "/bale", 4500, 20, "3 days", "Sun-cured Rhodes grass hay, 18 kg bales.", {"Weight":"18 kg","Grass":"Rhodes"}, None),
 ],
 'Spare Parts': [
  ("Tractor Tyre 18.4-30 (Rear)", "/tyre", 485000, 1, "5 days", "Radial rear tractor tyre, R1 tread, for 75–90 HP tractors.", {"Size":"18.4-30","Tread":"R1"}, [("", 485000), ("— 14.9-28", 365000), ("— front 7.50-16", 95000)]),
  ("Tractor Filter Service Kit (Oil, Fuel, Air)", "/kit", 48000, 1, "24 hrs", "Genuine-quality filters for Massey Ferguson and New Holland series.", {"Fits":"MF 375/385, NH TT75"}, None),
  ("Plough Disc Blades 26\" (Pack of 4)", "/pack", 145000, 1, "3 days", "Boron-steel replacement discs.", {"Size":"26 in","Count":"4"}, None),
  ("PTO Shaft (Heavy Duty, 1.2 m)", "", 85000, 1, "3 days", "Universal PTO shaft with shear-bolt clutch.", {"Length":"1.2 m","Series":"6"}, None),
  ("Rotavator Blades (Set of 48)", "/set", 96000, 1, "3 days", "L-type hardened blades for 1.8 m rotavators.", {"Count":"48"}, None),
 ],
},
'fertilizer': {
 'NPK Blends': [
  ("NPK 15-15-15 (50 kg)", "/bag", 38500, 5, "24 hrs", "Balanced granular fertilizer for maize, rice and vegetables at planting.", {"Analysis":"15-15-15","Bag":"50 kg","Form":"Granular"}, [("", 38500), ("— 20-10-10", 36500), ("— 12-12-17 + 2MgO", 42000), ("— 600 bags (truckload)", 22200000)]),
  ("NPK 27-13-13 (Rice Blend, 50 kg)", "/bag", 41000, 5, "24 hrs", "High-nitrogen blend formulated for lowland rice.", {"Analysis":"27-13-13","Bag":"50 kg"}, None),
  ("Vegetable Special NPK 10-10-30 + TE (25 kg)", "/bag", 32000, 2, "24 hrs", "Potassium-rich blend for fruiting vegetables and tubers.", {"Analysis":"10-10-30 + TE","Bag":"25 kg"}, None),
 ],
 'Urea': [
  ("Urea 46 % N (50 kg)", "/bag", 32000, 5, "24 hrs", "Granular urea for top-dressing maize, rice and sugarcane.", {"Nitrogen":"46 %","Bag":"50 kg"}, [("", 32000), ("— 600 bags (truckload)", 18600000)]),
  ("Urea Super Granules (Deep Placement, 50 kg)", "/bag", 36000, 5, "24 hrs", "Large urea briquettes for deep placement in rice — 30 % less nitrogen loss.", {"Nitrogen":"46 %","Form":"Briquette"}, None),
  ("Ammonium Sulphate 21 % N (50 kg)", "/bag", 24000, 5, "24 hrs", "Nitrogen plus sulphur source for onion, garlic and oil crops.", {"N":"21 %","S":"24 %"}, None),
  ("Calcium Ammonium Nitrate (50 kg)", "/bag", 34000, 5, "24 hrs", "Fast-acting nitrogen for vegetables and greenhouse crops.", {"N":"27 %"}, None),
 ],
 'Organic Compost': [
  ("Organic Compost (Composted Poultry Manure, 50 kg)", "/bag", 4500, 10, "2 days", "Fully composted, pathogen-free poultry manure enriched with neem cake.", {"Bag":"50 kg","N-P-K":"3-2-2","Organic matter":"55 %"}, [("", 4500), ("— 10 tonne truck", 650000)]),
  ("Vermicompost (25 kg)", "/bag", 8500, 5, "2 days", "Premium earthworm castings for nurseries, greenhouses and organic farms.", {"Bag":"25 kg"}, None),
  ("Cow Dung Manure (Dry, Trailer Load)", "/load", 85000, 1, "3 days", "Aged cattle manure from Kano ranches, ~5 tonnes per trailer.", {"Quantity":"~5 t"}, None),
  ("Neem Cake Organic Fertilizer (25 kg)", "/bag", 12500, 3, "2 days", "Dual-purpose soil conditioner and nematode suppressant.", {"Bag":"25 kg"}, None),
  ("Biochar Soil Amendment (20 kg)", "/bag", 9800, 3, "3 days", "Rice-husk biochar improving water and nutrient retention in sandy soils.", {"Bag":"20 kg"}, None),
 ],
 'Foliar Fertilizer': [
  ("Foliar NPK 20-20-20 + TE (1 kg)", "/kg", 5800, 5, "24 hrs", "Fully soluble foliar feed with chelated micronutrients.", {"Analysis":"20-20-20 + TE","Solubility":"100 %"}, [("", 5800), ("— 10-52-10 (root booster)", 6800), ("— 13-0-46 (fruiting)", 7500)]),
  ("Liquid Organic Foliar Fertilizer (1 L)", "/L", 4800, 5, "24 hrs", "Fish-emulsion and seaweed based liquid feed for organic production.", {"Volume":"1 L","Organic":"Yes"}, [("", 4800), ("— 5 L", 21000)]),
  ("Calcium Nitrate Foliar (1 kg)", "/kg", 4200, 5, "24 hrs", "Prevents blossom-end rot in tomato and pepper.", {"Ca":"19 %","N":"15.5 %"}, None),
  ("Boron Foliar (Solubor, 1 kg)", "/kg", 6500, 3, "24 hrs", "Corrects boron deficiency in oil palm, cocoa and vegetables.", {"B":"20 %"}, None),
 ],
 'Lime & Gypsum': [
  ("Agricultural Lime (Calcitic, 50 kg)", "/bag", 6500, 10, "3 days", "Finely ground limestone to correct soil acidity.", {"CaCO₃":"90 %","Bag":"50 kg"}, [("", 6500), ("— dolomitic", 7200)]),
  ("Gypsum (Agricultural, 50 kg)", "/bag", 7800, 10, "3 days", "Calcium sulphate for groundnut pegging and sodic soil reclamation.", {"Bag":"50 kg"}, None),
  ("Rock Phosphate (Sokoto, 50 kg)", "/bag", 9500, 5, "3 days", "Slow-release natural phosphate for acid soils and organic farms.", {"P₂O₅":"28 %"}, None),
 ],
 'Micronutrients': [
  ("Zinc Sulphate (25 kg)", "/bag", 28000, 2, "2 days", "Corrects zinc deficiency in rice and maize.", {"Zn":"21 %"}, None),
  ("Chelated Micronutrient Mix (EDTA, 1 kg)", "/kg", 9800, 3, "24 hrs", "Fe, Zn, Mn, Cu, B and Mo in chelated form for fertigation and foliar use.", {"Elements":"6","Form":"EDTA chelate"}, None),
  ("Iron Chelate Fe-EDDHA 6 % (1 kg)", "/kg", 14500, 2, "24 hrs", "Cures iron chlorosis in citrus, vegetables and hydroponics.", {"Fe":"6 %"}, None),
  ("Magnesium Sulphate (Epsom, 25 kg)", "/bag", 16500, 2, "2 days", "Fast magnesium and sulphur for oil palm, tomato and greenhouse crops.", {"MgO":"16 %"}, None),
 ],
},
'feed': {
 'Poultry Feed': [
  ("Broiler Starter Crumble (25 kg)", "/bag", 21500, 10, "24 hrs", "22 % protein starter with coccidiostat for 0–3 weeks.", {"Protein":"22 %","Form":"Crumble","Bag":"25 kg"}, [("", 21500), ("— finisher pellet (20 %)", 20500), ("— pre-starter (23 %)", 22500)]),
  ("Layer Mash (25 kg)", "/bag", 17800, 10, "24 hrs", "17 % protein layer ration with 3.8 % calcium for strong shells.", {"Protein":"17 %","Calcium":"3.8 %"}, [("", 17800), ("— grower mash", 16500), ("— chick mash", 18500)]),
  ("Turkey Grower Pellet (25 kg)", "/bag", 23500, 5, "24 hrs", "High-energy pellets for turkeys 8–20 weeks.", {"Protein":"20 %"}, None),
  ("Noiler / Cockerel Grower (25 kg)", "/bag", 16800, 10, "24 hrs", "Economical grower ration for dual-purpose birds.", {"Protein":"15 %"}, None),
 ],
 'Fish Feed': [
  ("Premium Floating Catfish Feed 4 mm (15 kg)", "/bag", 22800, 5, "24 hrs", "Imported-grade extruded feed, 42 % protein, high digestibility.", {"Pellet":"4 mm","Protein":"42 %"}, [("", 22800), ("— 2 mm (45 %)", 24000), ("— 6 mm (40 %)", 22000)]),
  ("Local Floating Feed 4 mm (15 kg)", "/bag", 17500, 10, "24 hrs", "Locally extruded floating feed offering strong value for grow-out.", {"Pellet":"4 mm","Protein":"38 %"}, None),
  ("Fish Feed Concentrate (30 %, 25 kg)", "/bag", 32000, 4, "24 hrs", "Vitamin-mineral protein concentrate for on-farm feed mixing.", {"Inclusion":"30 %"}, None),
 ],
 'Cattle & Goat Feed': [
  ("Dairy Cattle Concentrate (50 kg)", "/bag", 26500, 5, "2 days", "18 % protein concentrate to boost milk yield alongside forage.", {"Protein":"18 %","Bag":"50 kg"}, None),
  ("Goat & Sheep Fattening Pellet (25 kg)", "/bag", 14500, 5, "2 days", "Complete pellet for ram and goat fattening before festivals.", {"Protein":"16 %"}, None),
  ("Maize Silage (per Tonne)", "/tonne", 65000, 2, "3 days", "Fermented whole-plant maize silage in sealed bags.", {"Dry matter":"32 %"}, None),
  ("Cottonseed Cake (50 kg)", "/bag", 22000, 5, "2 days", "Protein-rich cake for ruminant rations.", {"Protein":"40 %"}, None),
  ("Wheat Bran / Offal (50 kg)", "/bag", 11500, 10, "24 hrs", "Digestible fibre and energy source for cattle and goats.", {"Bag":"50 kg"}, None),
 ],
 'Pig Feed': [
  ("Pig Grower Pellet (25 kg)", "/bag", 16500, 10, "24 hrs", "16 % protein grower ration for 20–60 kg pigs.", {"Protein":"16 %"}, [("", 16500), ("— weaner (18 %)", 18500), ("— finisher (14 %)", 15500)]),
  ("Sow Lactation Feed (25 kg)", "/bag", 19500, 5, "24 hrs", "High-energy ration supporting milk production and litter growth.", {"Protein":"17 %"}, None),
  ("Palm Kernel Cake (50 kg)", "/bag", 8500, 10, "24 hrs", "Economical energy and fibre ingredient for pig and cattle rations.", {"Bag":"50 kg"}, None),
 ],
 'Feed Concentrates': [
  ("Broiler Concentrate 5 % (25 kg)", "/bag", 38000, 2, "24 hrs", "Vitamin-mineral-amino-acid premix for on-farm broiler feed.", {"Inclusion":"5 %"}, [("", 38000), ("— layer 5 %", 36000)]),
  ("Fish Meal 65 % (50 kg)", "/bag", 145000, 1, "2 days", "Danish-grade fish meal for aqua and poultry feed.", {"Protein":"65 %"}, [("", 145000), ("— local 55 %", 96000)]),
  ("Lysine HCl 98.5 % (25 kg)", "/bag", 68000, 1, "2 days", "Feed-grade amino acid.", {"Purity":"98.5 %"}, [("", 68000), ("— DL-Methionine 99 %", 145000)]),
  ("Toxin Binder (25 kg)", "/bag", 42000, 1, "2 days", "Broad-spectrum mycotoxin binder for all species.", {"Inclusion":"1–2 kg/t"}, None),
  ("Bone Meal (50 kg)", "/bag", 18000, 5, "24 hrs", "Calcium and phosphorus source for poultry and pig rations.", {"Ca":"24 %","P":"12 %"}, None),
 ],
 'Raw Materials': [
  ("Feed-Grade Yellow Maize (100 kg)", "/bag", 68000, 10, "2 days", "Aflatoxin-tested feed maize, 13 % moisture.", {"Moisture":"13 %"}, None),
  ("Groundnut Cake (50 kg)", "/bag", 34000, 5, "2 days", "Expeller groundnut cake with 45 % protein.", {"Protein":"45 %"}, None),
  ("Brewers' Dried Grain (50 kg)", "/bag", 9500, 10, "2 days", "Dried spent grain from breweries, good fibre and protein.", {"Protein":"22 %"}, None),
  ("Cassava Peels (Dried, 50 kg)", "/bag", 5500, 10, "2 days", "Sun-dried cassava peel meal for ruminant and pig feed.", {"Bag":"50 kg"}, None),
  ("Limestone Granules (50 kg)", "/bag", 4500, 10, "24 hrs", "Feed-grade calcium carbonate.", {"Ca":"38 %"}, None),
 ],
 'Feed Mills': [
  ("Feed Pellet Mill (Electric, 500 kg/hr)", "", 1850000, 1, "10 days", "Flat-die pellet mill with 3 mm and 5 mm dies for poultry and fish feed.", {"Capacity":"500 kg/hr","Motor":"15 HP"}, [("", 1850000), ("— 1 t/hr", 3200000)]),
  ("Hammer Mill + Mixer Set (1 t/hr)", "/set", 2650000, 1, "10 days", "Grinder and vertical mixer for on-farm feed production.", {"Capacity":"1 t/hr"}, None),
  ("Floating Fish Feed Extruder (200 kg/hr)", "", 4500000, 1, "14 days", "Dry-type extruder producing floating pellets 2–8 mm.", {"Capacity":"200 kg/hr"}, None),
  ("Toll Milling Service (per Tonne)", "/tonne", 18000, 1, "By schedule", "We grind, mix and pellet your formulation at our mill.", {"Min":"1 tonne"}, None),
 ],
},
'fruits': {
 'Tomatoes & Peppers': [
  ("Fresh Tomatoes (Roma, 50 kg Crate)", "/crate", 28000, 5, "Same day", "Firm Roma tomatoes harvested at breaker stage for long shelf life; crated to reduce bruising.", {"Variety":"Roma VF","Crate":"50 kg","Grade":"A"}, [("", 28000), ("— UTC / Padma", 30000), ("— cherry (10 kg)", 15000)]),
  ("Habanero Pepper — Atarodo (50 kg Bag)", "/bag", 65000, 2, "Same day", "Fiery red habanero from Kaduna, sorted and bagged.", {"Type":"Habanero","Bag":"50 kg"}, None),
  ("Bell Pepper — Tatashe (25 kg)", "/bag", 32000, 2, "Same day", "Sweet red tatashe for stews and processing.", {"Bag":"25 kg"}, None),
  ("Cayenne — Shombo (25 kg)", "/bag", 24000, 2, "Same day", "Long red shombo pepper.", {"Bag":"25 kg"}, None),
  ("Dried Chilli Pepper (25 kg)", "/bag", 85000, 1, "2 days", "Sun-dried whole chillies, low moisture, export grade.", {"Moisture":"< 10 %"}, None),
 ],
 'Leafy Greens': [
  ("Ugu — Fluted Pumpkin Leaves (Bundle of 20)", "/bundle", 8000, 5, "Same day", "Tender ugu leaves harvested at dawn from irrigated beds.", {"Count":"20 bunches","Harvest":"Same morning"}, None),
  ("Spinach — Green Amaranth (Crate)", "/crate", 6500, 5, "Same day", "Fresh tete amaranth, washed and crated.", {"Weight":"~10 kg"}, None),
  ("Lettuce (Iceberg, Crate of 12)", "/crate", 12000, 3, "Same day", "Crisp greenhouse iceberg for hotels and retail.", {"Count":"12 heads"}, [("", 12000), ("— romaine", 11000)]),
  ("Cabbage (Bag of 20 Heads)", "/bag", 18000, 2, "Same day", "Jos Plateau cabbage, firm heads 1.5–2 kg.", {"Count":"20"}, None),
  ("Scent Leaf — Efirin (Bundle of 20)", "/bundle", 5000, 5, "Same day", "Aromatic basil for cooking and herbal use.", {"Count":"20 bunches"}, None),
  ("Kale & Swiss Chard Mix (5 kg)", "/box", 9500, 2, "Same day", "Greenhouse-grown salad greens for premium kitchens.", {"Weight":"5 kg"}, None),
 ],
 'Onions & Garlic': [
  ("Red Onions (Sokoto, 100 kg Bag)", "/bag", 95000, 2, "2 days", "Well-cured Sokoto red onions with tight skins and long storage life.", {"Bag":"100 kg","Origin":"Sokoto"}, [("", 95000), ("— white onions", 88000), ("— 50 kg", 49000)]),
  ("Garlic (Local, 25 kg)", "/bag", 68000, 1, "2 days", "Pungent local garlic from Kano.", {"Bag":"25 kg"}, None),
  ("Spring Onions (Crate)", "/crate", 7500, 3, "Same day", "Fresh green spring onions.", {"Weight":"~8 kg"}, None),
  ("Ginger (Fresh, 50 kg)", "/bag", 85000, 1, "2 days", "Kaduna fresh ginger rhizomes.", {"Bag":"50 kg"}, None),
 ],
 'Mangoes & Citrus': [
  ("Sweet Oranges (Benue, 100 kg Bag)", "/bag", 42000, 2, "2 days", "Juicy Valencia-type oranges, sorted by size.", {"Bag":"~300 fruits","Origin":"Benue"}, [("", 42000), ("— tangerine", 48000), ("— grapefruit", 40000)]),
  ("Mangoes (Julie / Ogbomoso, 50 kg Crate)", "/crate", 32000, 2, "Same day", "Sweet local mangoes at mature-green stage for ripening.", {"Variety":"Julie","Crate":"50 kg"}, [("", 32000), ("— Kent / Keitt (export)", 55000)]),
  ("Lemons & Limes (25 kg)", "/bag", 22000, 2, "2 days", "Fresh limes for juice and processing.", {"Bag":"25 kg"}, None),
  ("Pawpaw — Papaya (Crate of 20)", "/crate", 18000, 2, "Same day", "Solo and local papaya, half-ripe.", {"Count":"20"}, None),
  ("Avocado (Crate of 50)", "/crate", 28000, 2, "Same day", "Fresh local avocados, firm and green.", {"Count":"50"}, None),
 ],
 'Pineapples & Bananas': [
  ("Pineapples (Smooth Cayenne, 20 pcs)", "/pack", 22000, 2, "Same day", "Large sweet pineapples from Benin farms, 1.5–2 kg each.", {"Count":"20","Variety":"Smooth Cayenne"}, [("", 22000), ("— Sugarloaf", 20000), ("— MD2 (export)", 34000)]),
  ("Bananas (Cavendish, 40 kg Bunch)", "/bunch", 24000, 2, "Same day", "Green Cavendish bananas for ripening rooms and retail.", {"Weight":"~40 kg"}, None),
  ("Plantain (Bunch, 25–30 kg)", "/bunch", 18000, 3, "Same day", "Mature green plantain bunches from Ondo.", {"Weight":"25–30 kg"}, [("", 18000), ("— ripe", 19500)]),
  ("Coconuts (Bag of 100)", "/bag", 45000, 1, "2 days", "Mature dry coconuts from Badagry.", {"Count":"100"}, None),
 ],
 'Watermelon': [
  ("Watermelon (Large, 10 pcs)", "/pack", 32000, 2, "Same day", "Sweet Sugar Baby watermelons 8–10 kg each, harvested ripe.", {"Count":"10","Weight":"8–10 kg each"}, [("", 32000), ("— truckload (500 pcs)", 1400000)]),
  ("Seedless Watermelon (5 pcs)", "/pack", 24000, 2, "Same day", "Premium seedless hybrid for supermarkets.", {"Count":"5"}, None),
  ("Sweet Melon — Cantaloupe (Crate of 12)", "/crate", 18000, 2, "Same day", "Greenhouse cantaloupe, aromatic and sweet.", {"Count":"12"}, None),
  ("Cucumber (50 kg Bag)", "/bag", 22000, 3, "Same day", "Dark-green cucumbers, firm and uniform.", {"Bag":"50 kg"}, None),
 ],
 'Export Grade': [
  ("Export Mangoes (Kent, 4 kg Carton)", "/carton", 9500, 50, "3 days", "GlobalG.A.P.-compliant Kent mangoes, hot-water treated, packed for EU and Gulf markets.", {"Carton":"4 kg","Certification":"GlobalG.A.P.","Treatment":"Hot water"}, None),
  ("Export Chilli — Fresh Habanero (5 kg Carton)", "/carton", 18000, 40, "3 days", "Sorted, stem-on habaneros with phytosanitary certificate.", {"Carton":"5 kg","Cert":"Phytosanitary"}, None),
  ("Export Pineapple MD2 (12 kg Carton)", "/carton", 22000, 50, "3 days", "Sea-freight ready MD2 pineapples, crown-on.", {"Carton":"12 kg"}, None),
  ("Export Ginger (Dried Split, 20 kg)", "/bag", 96000, 10, "5 days", "Dried split ginger, 8 % moisture, export grade.", {"Moisture":"8 %"}, None),
  ("Hibiscus — Zobo Flowers (Export, 50 kg)", "/bag", 145000, 5, "5 days", "Cleaned dried hibiscus calyces for export.", {"Bag":"50 kg"}, None),
 ],
},
'produce': {
 'Yam & Cassava': [
  ("Gari — Ijebu White (50 kg)", "/bag", 42000, 2, "2 days", "Sour, crisp Ijebu gari processed hygienically and sun-dried.", {"Bag":"50 kg","Type":"White (Ijebu)"}, [("", 42000), ("— yellow (palm oil)", 44000), ("— 25 kg", 22000)]),
  ("High-Quality Cassava Flour — HQCF (50 kg)", "/bag", 38000, 5, "3 days", "Unfermented, odourless cassava flour for bakeries and industry.", {"Bag":"50 kg","Moisture":"< 12 %"}, None),
  ("Cassava Starch (Food Grade, 50 kg)", "/bag", 52000, 5, "3 days", "Native cassava starch for food, textile and pharma uses.", {"Purity":"99 %"}, None),
  ("Fufu / Akpu (Wet, 25 kg)", "/bag", 12500, 2, "Same day", "Fresh fermented cassava fufu.", {"Bag":"25 kg"}, None),
  ("Pounded Yam Flour (Elubo, 25 kg)", "/bag", 36000, 2, "2 days", "Fine yam flour for amala and pounded yam.", {"Bag":"25 kg"}, None),
 ],
 'Palm Oil': [
  ("Red Palm Oil (25 L Keg)", "/keg", 62000, 2, "2 days", "Fresh, unadulterated red palm oil from Ondo mills, low FFA.", {"Volume":"25 L","FFA":"< 5 %"}, [("", 62000), ("— 5 L", 13500), ("— 1,000 L (IBC)", 2350000)]),
  ("Palm Kernel Oil (25 L)", "/keg", 58000, 2, "2 days", "Cold-pressed PKO for soap and cosmetics.", {"Volume":"25 L"}, None),
  ("Fresh Palm Fruit Bunches (Tonne)", "/tonne", 85000, 2, "24 hrs", "Tenera FFB delivered to your mill within 24 hours of harvest.", {"Variety":"Tenera","OER":"20 %+"}, None),
  ("Palm Kernel Nuts (Tonne)", "/tonne", 320000, 1, "3 days", "Cracked, dry palm kernels.", {"Moisture":"< 8 %"}, None),
 ],
 'Honey': [
  ("Pure Raw Honey (5 L Jar)", "/jar", 32000, 1, "2 days", "Unheated, unfiltered forest honey from Oyo bee farms; lab-tested with no additives.", {"Volume":"5 L","Processing":"Raw","Origin":"Oyo"}, [("", 32000), ("— 1 L", 7500), ("— 25 L bucket", 145000)]),
  ("Comb Honey (1 kg)", "/kg", 9500, 2, "2 days", "Cut comb honey in its natural wax.", {"Weight":"1 kg"}, None),
  ("Beeswax (Refined, 5 kg)", "/block", 28000, 1, "3 days", "Clean yellow beeswax for cosmetics and candles.", {"Weight":"5 kg"}, None),
  ("Langstroth Beehive (Complete)", "", 48000, 2, "5 days", "Ten-frame Langstroth hive with super, frames and stand.", {"Frames":"10","Wood":"Treated"}, [("", 48000), ("— Kenyan top-bar hive", 32000)]),
  ("Beekeeping Starter Kit (Suit, Smoker, Tools)", "/kit", 65000, 1, "3 days", "Full suit, veil, gloves, smoker, hive tool and brush.", {"Pieces":"6"}, None),
 ],
 'Spices & Herbs': [
  ("Dried Ginger (Split, 25 kg)", "/bag", 118000, 1, "3 days", "Kaduna dried ginger with high oleoresin.", {"Bag":"25 kg","Moisture":"8 %"}, None),
  ("Turmeric Powder (10 kg)", "/bag", 42000, 1, "3 days", "Bright turmeric powder milled from Cross River rhizomes.", {"Curcumin":"3 %+"}, None),
  ("Black Pepper (Uziza, 5 kg)", "/bag", 65000, 1, "3 days", "Aromatic uziza seeds.", {"Weight":"5 kg"}, None),
  ("Locust Bean — Iru / Dawadawa (10 kg)", "/bag", 28000, 1, "2 days", "Fermented locust bean seasoning.", {"Weight":"10 kg"}, None),
  ("Sesame Seed (Food Grade, 50 kg)", "/bag", 135000, 1, "3 days", "Cleaned white sesame, 99 % purity, from Benue.", {"Purity":"99 %"}, None),
  ("Moringa Leaf Powder (5 kg)", "/bag", 32000, 1, "3 days", "Shade-dried moringa powder.", {"Weight":"5 kg"}, None),
 ],
 'Dairy Products': [
  ("Fresh Cow Milk (Chilled, 20 L)", "/can", 24000, 2, "Same day", "Pasteurised whole milk from Friesian crossbreeds, chilled within 2 hours of milking.", {"Volume":"20 L","Fat":"3.8 %","Pasteurised":"Yes"}, None),
  ("Wara — Fresh Cheese (5 kg)", "/pack", 14500, 2, "Same day", "Traditional soft cheese made daily.", {"Weight":"5 kg"}, None),
  ("Nono / Fermented Yoghurt (10 L)", "/keg", 12000, 2, "Same day", "Cultured milk drink, unsweetened.", {"Volume":"10 L"}, None),
  ("Goat Milk (Fresh, 5 L)", "/keg", 9500, 2, "Same day", "Fresh goat milk from West African dwarf goats.", {"Volume":"5 L"}, None),
  ("Kilishi — Dried Spiced Beef (2 kg)", "/pack", 38000, 1, "2 days", "Premium sun-dried spiced beef jerky from Kano.", {"Weight":"2 kg"}, None),
 ],
 'Mushrooms': [
  ("Fresh Oyster Mushrooms (5 kg)", "/box", 22500, 1, "Same day", "Grey oyster mushrooms grown on sterilised sawdust substrate.", {"Weight":"5 kg","Variety":"Pleurotus"}, [("", 22500), ("— dried 1 kg", 24000)]),
  ("Mushroom Spawn (Oyster, 1 kg)", "/bag", 4500, 5, "3 days", "Grain spawn with vigorous mycelium.", {"Weight":"1 kg"}, None),
  ("Ready-to-Fruit Mushroom Bags (Pack of 20)", "/pack", 28000, 1, "3 days", "Fully colonised substrate bags — fruit in 7 days.", {"Count":"20"}, None),
  ("Mushroom Farming Training (2 days)", "/person", 35000, 1, "Monthly", "Practical substrate preparation, spawning and harvesting course.", {"Duration":"2 days"}, None),
 ],
 'Cocoa & Cashew': [
  ("Cocoa Beans (Fermented & Dried, 64 kg)", "/bag", 285000, 5, "5 days", "Grade 1 fermented cocoa from Ondo, 7 % moisture, bean count 95/100 g.", {"Grade":"1","Moisture":"7 %","Bag":"64 kg"}, [("", 285000), ("— 10 tonnes", 43500000)]),
  ("Raw Cashew Nuts (80 kg Bag)", "/bag", 165000, 5, "5 days", "RCN from Kogi, 48+ lbs out-turn.", {"Out-turn":"48 lbs","Bag":"80 kg"}, None),
  ("Cashew Kernels (W320, 22.68 kg Carton)", "/carton", 245000, 1, "5 days", "Processed white whole kernels, vacuum packed.", {"Grade":"W320"}, None),
  ("Cocoa Powder (Natural, 25 kg)", "/bag", 165000, 1, "5 days", "10–12 % fat natural cocoa powder.", {"Fat":"10–12 %"}, None),
  ("Kola Nuts (Bag of 1,000)", "/bag", 85000, 1, "3 days", "Fresh red and white kola nuts.", {"Count":"1,000"}, None),
 ],
},
'processing': {
 'Rice Mills': [
  ("Rice Mill Complete Line (2 t/hr)", "/line", 28500000, 1, "45 days", "Destoner, husker, paddy separator, whitener, polisher, grader and colour sorter with installation.", {"Capacity":"2 t/hr","Includes":"Installation + training"}, [("", 28500000), ("— 1 t/hr", 16500000)]),
  ("Combined Rice Mill (Small, 500 kg/hr)", "", 2400000, 1, "10 days", "Compact mill with husker, whitener and blower.", {"Capacity":"500 kg/hr","Motor":"15 HP"}, None),
  ("Paddy Parboiling Plant (5 t/day)", "", 6500000, 1, "30 days", "Steam parboiling vessels and mechanical dryer.", {"Capacity":"5 t/day"}, None),
  ("Rice Destoner (1 t/hr)", "", 850000, 1, "7 days", "Gravity destoner removing stones and heavy impurities.", {"Capacity":"1 t/hr"}, None),
  ("Rice Milling Service (per Tonne of Paddy)", "/tonne", 22000, 1, "By schedule", "Toll milling with parboiling, destoning and polishing.", {"Min":"1 tonne"}, None),
 ],
 'Cassava Processors': [
  ("Cassava Grater (Diesel, 3 t/hr)", "", 650000, 1, "5 days", "Heavy-duty grater with stainless drum.", {"Capacity":"3 t/hr","Engine":"8 HP diesel"}, [("", 650000), ("— electric 2 t/hr", 480000)]),
  ("Hydraulic Cassava Press (Double Jack)", "", 320000, 1, "5 days", "Dewatering press for grated mash.", {"Capacity":"1 t/batch"}, None),
  ("Gari Fryer (Stainless, Mechanised)", "", 1450000, 1, "10 days", "Rotary gari fryer with gas heating and stirrer.", {"Capacity":"300 kg/hr"}, None),
  ("Cassava Peeler (Automatic, 1 t/hr)", "", 1850000, 1, "14 days", "Reduces peeling labour by 90 %.", {"Capacity":"1 t/hr"}, None),
  ("Flash Dryer (HQCF, 1 t/hr)", "", 12500000, 1, "45 days", "Pneumatic flash dryer for cassava flour and starch.", {"Capacity":"1 t/hr"}, None),
 ],
 'Oil Presses': [
  ("Palm Oil Mill (Small Scale, 1 t FFB/hr)", "/line", 8500000, 1, "30 days", "Steriliser, thresher, digester-screw press, clarifier and boiler.", {"Capacity":"1 t FFB/hr"}, None),
  ("Screw Oil Press (Groundnut / Soybean, 100 kg/hr)", "", 950000, 1, "7 days", "Automatic screw expeller with heater and filter.", {"Capacity":"100 kg/hr","Motor":"7.5 kW"}, [("", 950000), ("— 300 kg/hr", 2400000)]),
  ("Palm Kernel Cracker & Separator", "", 780000, 1, "7 days", "Cracks nuts and separates shells from kernels.", {"Capacity":"1 t/hr"}, None),
  ("Shea Butter Processing Kit", "/kit", 1250000, 1, "14 days", "Crusher, roaster, mill and kneader for shea processing.", {"Capacity":"200 kg/day"}, None),
 ],
 'Feed Pelletizers': [
  ("Ring-Die Pellet Mill (2 t/hr)", "", 9800000, 1, "30 days", "Industrial ring-die pelletiser with conditioner for commercial feed mills.", {"Capacity":"2 t/hr","Motor":"55 kW"}, None),
  ("Flat-Die Pellet Machine (300 kg/hr)", "", 850000, 1, "7 days", "Compact pelletiser for poultry, rabbit and fish sinking feed.", {"Capacity":"300 kg/hr"}, None),
  ("Pellet Cooler & Crumbler", "", 1650000, 1, "14 days", "Counter-flow cooler with crumbler rollers.", {"Capacity":"2 t/hr"}, None),
 ],
 'Packaging Lines': [
  ("Semi-Automatic Bagging Scale (5–50 kg)", "", 1450000, 1, "14 days", "Weigh-filling station for grains and feed with stitching machine.", {"Range":"5–50 kg","Speed":"300 bags/hr"}, None),
  ("Bag Stitching Machine (Portable)", "", 85000, 1, "3 days", "Hand-held sack closer for jute and PP bags.", {"Type":"Portable"}, None),
  ("Vertical Form-Fill-Seal Machine (Granules)", "", 4500000, 1, "30 days", "Automatic sachet packing for rice, beans, gari and seed.", {"Range":"100 g – 5 kg"}, None),
  ("Fruit & Vegetable Grading Line", "", 6800000, 1, "45 days", "Washer, dryer and size grader for citrus, tomato and onion.", {"Capacity":"3 t/hr"}, None),
  ("Vacuum Sealer (Commercial)", "", 285000, 1, "5 days", "Double-chamber vacuum packer for smoked fish, kilishi and kernels.", {"Chamber":"Double"}, None),
 ],
 'Dryers': [
  ("Solar Tunnel Dryer (100 kg batch)", "", 850000, 1, "14 days", "Hygienic solar dryer for fruits, vegetables, fish and cocoa.", {"Capacity":"100 kg/batch"}, None),
  ("Mechanical Grain Dryer (10 t batch)", "", 14500000, 1, "45 days", "Diesel/biomass-fired recirculating dryer for paddy and maize.", {"Capacity":"10 t/batch"}, None),
  ("Cabinet Dryer (Electric, 24 Trays)", "", 1250000, 1, "10 days", "Stainless food dehydrator for pepper, ginger and herbs.", {"Trays":"24"}, None),
  ("Fish Smoking Kiln (Charcoal / Gas, 200 kg)", "", 650000, 1, "10 days", "Improved smoking kiln with drip tray and thermometer.", {"Capacity":"200 kg"}, [("", 650000), ("— 50 kg", 220000)]),
 ],
 'Cold Rooms': [
  ("Walk-in Cold Room (20 ft, Chiller)", "", 9500000, 1, "30 days", "Insulated 20 ft cold room with condensing unit for fruits and vegetables at 2–8 °C.", {"Size":"20 ft","Temperature":"2–8 °C"}, [("", 9500000), ("— freezer (-18 °C)", 12500000), ("— 40 ft chiller", 16500000)]),
  ("Solar-Powered Cold Room (10 ft)", "", 14500000, 1, "45 days", "Off-grid solar cold room with thermal storage for markets.", {"Size":"10 ft","Power":"Solar"}, None),
  ("Blast Freezer (500 kg / batch)", "", 8800000, 1, "30 days", "Rapid freezing for poultry and fish processors.", {"Capacity":"500 kg"}, None),
  ("Cold Room Rental (per Pallet per Week)", "/pallet-week", 12000, 1, "Same day", "Chilled or frozen pallet storage in Lagos.", {"Temp":"Chill or frozen"}, None),
 ],
},
}
