# Catalogue spec, part A — poultry, livestock, fisheries, crops, seeds, agrochem
# item = (name, unit, price, moq, delivery, desc, specs, variants)   variants = [(label, price), ...] or None
SPEC_A = {
'poultry': {
 'Day-Old Chicks': [
  ("Day-Old Broiler Chicks (Arbor Acres Plus)", "/chick", 470, 50, "24–48 hrs", "Fast-growing Arbor Acres broiler chicks, vaccinated against Marek's and Newcastle, from a NAPRI-inspected hatchery.", {"Breed":"Arbor Acres Plus","Vaccination":"Marek's + NDV","Hatch days":"Mon / Thu"}, [("", 470), ("— 500+ chicks", 445), ("— 2,000+ chicks", 425)]),
  ("Day-Old Broiler Chicks (Ross 308)", "/chick", 490, 50, "24–48 hrs", "Uniform Ross 308 chicks with excellent feed conversion; reach 2.4 kg live weight in 6 weeks on standard feed.", {"Breed":"Ross 308","Vaccination":"Marek's + NDV + IB","Parent stock":"Imported"}, None),
  ("Day-Old Pullets (ISA Brown)", "/chick", 620, 50, "48 hrs", "Sexed ISA Brown layer chicks with 90 %+ sexing accuracy; peak production 320 eggs per hen-year.", {"Breed":"ISA Brown","Sex":"Female","Vaccination":"Marek's"}, [("", 620), ("— 1,000+ chicks", 590)]),
  ("Day-Old Noiler Chicks (Dual Purpose)", "/chick", 520, 50, "48 hrs", "Hardy dual-purpose Noiler chicks suited to backyard and free-range systems; good meat and egg yield.", {"Breed":"Noiler","Type":"Dual purpose","Vaccination":"Marek's + NDV"}, None),
  ("Day-Old Cockerels (Black Harco)", "/chick", 260, 100, "48 hrs", "Economical Black Harco cockerels for festive-season meat production; disease tolerant and forage well.", {"Breed":"Black Harco","Sex":"Male","Market age":"16–20 weeks"}, None),
 ],
 'Broilers': [
  ("Live Broilers 2.0–2.5 kg", "/bird", 7800, 10, "Same day", "Farm-fresh live broilers raised on quality feed with full vaccination records; ideal for events and retail.", {"Live weight":"2.0–2.5 kg","Age":"6–7 weeks","Feed":"Commercial pellets"}, [("", 7800), ("— 100+ birds", 7400)]),
  ("Live Broilers 3.0 kg+ (Jumbo)", "/bird", 10500, 5, "Same day", "Heavy jumbo broilers for catering and festive demand; 3 kg and above live weight.", {"Live weight":"3.0 kg+","Age":"8–9 weeks"}, None),
  ("Dressed Broiler Chicken (Frozen, 1.5 kg)", "/bird", 8200, 5, "24 hrs", "Hygienically processed and blast-frozen whole chicken, NAFDAC-compliant packaging.", {"Dressed weight":"1.4–1.6 kg","Packaging":"Vacuum bag","Storage":"-18 °C"}, [("", 8200), ("— carton of 10", 79000)]),
  ("Chicken Parts (Laps & Wings, 5 kg)", "/pack", 22000, 2, "24 hrs", "Portioned broiler laps and wings, cleaned and frozen; popular with restaurants.", {"Pack":"5 kg","Cut":"Laps / wings","Storage":"Frozen"}, None),
 ],
 'Layers & Pullets': [
  ("Point-of-Lay Pullets (ISA Brown, 16 wks)", "/bird", 4200, 20, "2–3 days", "Fully vaccinated 16-week ISA Brown pullets, debeaked and ready to come into lay within 3 weeks.", {"Breed":"ISA Brown","Age":"16 weeks","Vaccines":"Full programme"}, [("", 4200), ("— 18 weeks", 4600), ("— 200+ birds", 4000)]),
  ("Point-of-Lay Pullets (Lohmann Brown)", "/bird", 4400, 20, "2–3 days", "Lohmann Brown pullets with strong shell quality and calm temperament; 18 weeks old.", {"Breed":"Lohmann Brown","Age":"18 weeks"}, None),
  ("Grower Pullets (8 weeks)", "/bird", 2300, 50, "3 days", "Well-brooded 8-week pullets for farmers who prefer to finish rearing themselves.", {"Age":"8 weeks","Breed":"ISA Brown"}, None),
  ("Spent Layers (Old Layers)", "/bird", 3200, 20, "Same day", "Culled layers at end of lay, healthy and heavy — excellent for stews and pepper soup.", {"Age":"72+ weeks","Weight":"1.8–2.2 kg"}, None),
 ],
 'Turkeys & Ducks': [
  ("Turkey Poults (Broad Breasted White, 4 wks)", "/poult", 6500, 5, "3 days", "Brooded 4-week turkey poults, vaccinated; grow to 8–10 kg in 20 weeks.", {"Breed":"Broad Breasted White","Age":"4 weeks"}, [("", 6500), ("— day-old", 3400)]),
  ("Mature Turkey (Live, 8–10 kg)", "/bird", 45000, 1, "Same day", "Farm-raised live turkeys for Christmas and events; weights 8–10 kg.", {"Weight":"8–10 kg","Age":"20–24 weeks"}, None),
  ("Pekin Ducklings (Day-old)", "/duckling", 1500, 10, "3 days", "Fast-growing Pekin ducklings; table weight 3 kg in 8 weeks.", {"Breed":"Pekin","Age":"Day-old"}, None),
  ("Muscovy Ducks (Mature Pair)", "/pair", 24000, 1, "2 days", "Breeding pair of Muscovy ducks, hardy and excellent natural mothers.", {"Breed":"Muscovy","Age":"6+ months"}, None),
  ("Guinea Fowl Keets (Day-old)", "/keet", 900, 20, "3 days", "Healthy guinea fowl keets; hardy foragers with premium-priced meat.", {"Type":"Pearl grey","Age":"Day-old"}, None),
 ],
 'Table Eggs': [
  ("Fresh Table Eggs (Large, Crate of 30)", "/crate", 4600, 5, "Same day", "Farm-fresh large eggs, collected daily, candled and graded. Crate of 30.", {"Size":"Large 60 g+","Colour":"Brown","Shelf life":"21 days"}, [("", 4600), ("— medium", 4300), ("— 50+ crates", 4400)]),
  ("Jumbo Eggs (Crate of 30)", "/crate", 5200, 5, "Same day", "Extra-large jumbo eggs 70 g+, from mature layers on high-calcium feed.", {"Size":"Jumbo 70 g+","Colour":"Brown"}, None),
  ("Fertile Hatching Eggs (Broiler)", "/egg", 260, 100, "24 hrs", "Fertile broiler hatching eggs from parent stock; 85 %+ hatchability guaranteed with proper incubation.", {"Type":"Broiler parent stock","Fertility":"90 %+"}, [("", 260), ("— layer (ISA Brown)", 240), ("— Noiler", 220)]),
  ("Quail Eggs (Tray of 50)", "/tray", 2600, 5, "Same day", "Nutrient-rich fresh quail eggs, cleaned and packed in trays of 50.", {"Count":"50","Shelf life":"14 days"}, None),
 ],
 'Hatchery Equipment': [
  ("Automatic Egg Incubator (528 eggs)", "", 485000, 1, "5–7 days", "Fully automatic incubator with digital temperature and humidity control, auto turning and hatching trays.", {"Capacity":"528 eggs","Power":"220 V / 120 W","Turning":"Automatic"}, [("", 485000), ("— 264 eggs", 295000), ("— 1,056 eggs", 890000), ("— 5,280 eggs", 3600000)]),
  ("Mini Incubator (56 eggs)", "", 78000, 1, "3 days", "Compact digital incubator for small farms and schools, automatic turning and clear viewing window.", {"Capacity":"56 eggs","Power":"80 W"}, None),
  ("Egg Candler (LED)", "", 6500, 1, "2 days", "High-intensity LED candler for checking fertility and embryo development.", {"Power":"Rechargeable","Type":"LED"}, None),
  ("Hatchery Setter Trays (Pack of 10)", "/pack", 28000, 1, "3 days", "Durable plastic setter trays compatible with common cabinet incubators.", {"Eggs per tray":"88","Material":"Food-grade plastic"}, None),
 ],
 'Poultry Housing': [
  ("Battery Cage (Galvanised, 96 birds)", "/set", 245000, 1, "5–7 days", "Hot-dip galvanised A-type layer cage, 3 tiers, 96-bird capacity with feeders, nipple drinkers and egg trays.", {"Capacity":"96 birds","Tiers":"3","Material":"Galvanised steel"}, [("", 245000), ("— 128 birds", 320000), ("— 160 birds", 395000)]),
  ("Automatic Nipple Drinker Line (30 m)", "/line", 185000, 1, "5 days", "Complete nipple drinking line with regulator, nipples every 25 cm and drip cups.", {"Length":"30 m","Nipples":"120"}, None),
  ("Plastic Chick Feeder (5 kg, Pack of 10)", "/pack", 18500, 1, "2 days", "Hanging tube feeders for broilers and pullets, anti-waste lip, easy to clean.", {"Capacity":"5 kg","Pack":"10 pieces"}, [("", 18500), ("— 10 kg feeders", 26000)]),
  ("Brooder Heater (Gas, 1,000 chicks)", "", 62000, 1, "3 days", "Infrared gas brooder for 1,000 day-old chicks; steady, fuel-efficient heat.", {"Capacity":"1,000 chicks","Fuel":"LPG"}, None),
  ("Deep-Litter Wood Shavings (Bale)", "/bale", 3200, 10, "24 hrs", "Dry, dust-extracted softwood shavings for poultry bedding; 20 kg compressed bale.", {"Weight":"20 kg","Moisture":"< 15 %"}, None),
 ],
},
'livestock': {
 'Cattle & Bulls': [
  ("White Fulani Bull (350–400 kg)", "/head", 780000, 1, "3–5 days", "Grass-fed White Fulani bull, vet-inspected, dewormed and vaccinated; suitable for beef or breeding.", {"Breed":"White Fulani","Weight":"350–400 kg","Age":"3–4 years"}, [("", 780000), ("— 450 kg+", 950000)]),
  ("Sokoto Gudali Heifer", "/head", 520000, 1, "3–5 days", "Young Gudali heifer from a healthy herd, ready for breeding; docile and heat tolerant.", {"Breed":"Sokoto Gudali","Age":"2 years","Status":"Open"}, None),
  ("Red Bororo Bull (Festive)", "/head", 680000, 1, "3 days", "Healthy Red Bororo bull for Sallah and celebrations, delivered by licensed livestock truck.", {"Breed":"Red Bororo","Weight":"300–350 kg"}, None),
  ("Friesian × Bunaji Dairy Cow (In-milk)", "/head", 1250000, 1, "5–7 days", "Crossbred dairy cow producing 10–12 L per day, currently in second lactation.", {"Breed":"Friesian × Bunaji","Yield":"10–12 L/day","Lactation":"2nd"}, None),
  ("Weaner Calves (Mixed Breeds)", "/head", 210000, 2, "3 days", "Weaned calves 6–8 months old for fattening programmes; vaccinated against CBPP.", {"Age":"6–8 months","Vaccines":"CBPP, FMD"}, None),
 ],
 'Goats': [
  ("Red Sokoto Buck (Mature)", "/head", 95000, 1, "2 days", "Prime Red Sokoto (Maradi) buck, 30–35 kg, ideal for breeding or festive slaughter.", {"Breed":"Red Sokoto","Weight":"30–35 kg","Age":"18–24 months"}, [("", 95000), ("— doe", 72000)]),
  ("West African Dwarf Goats (Pair)", "/pair", 110000, 1, "2 days", "Hardy WAD breeding pair, trypanotolerant and prolific; excellent for southern farms.", {"Breed":"West African Dwarf","Age":"12–18 months"}, None),
  ("Boer Cross Kids (4 months)", "/head", 85000, 2, "3 days", "Fast-growing Boer × Sokoto kids with strong meat conformation.", {"Breed":"Boer cross","Age":"4 months"}, None),
  ("Sahel Goats (Batch of 10)", "/batch", 650000, 1, "3–5 days", "Batch of ten Sahel goats sourced from northern markets, quarantined and dewormed.", {"Breed":"Sahel","Count":"10","Weight":"25–30 kg"}, None),
 ],
 'Sheep & Rams': [
  ("Uda Ram (Sallah Grade, 45 kg+)", "/head", 260000, 1, "2–3 days", "Well-fed Uda ram with full horns, 45 kg and above; premium festive grade.", {"Breed":"Uda","Weight":"45 kg+","Age":"2 years"}, [("", 260000), ("— 60 kg+", 380000)]),
  ("Balami Ram (Large Frame)", "/head", 320000, 1, "2–3 days", "Large-framed Balami ram, healthy and vaccinated against PPR.", {"Breed":"Balami","Weight":"50–55 kg"}, None),
  ("Yankasa Ewes (Breeding, Batch of 5)", "/batch", 450000, 1, "3 days", "Five young Yankasa ewes for flock establishment; twinning lines.", {"Breed":"Yankasa","Count":"5","Age":"12–18 months"}, None),
  ("West African Dwarf Sheep (Pair)", "/pair", 120000, 1, "2 days", "Hardy WAD sheep pair adapted to humid zones; low maintenance.", {"Breed":"WAD","Age":"1 year"}, None),
 ],
 'Pigs & Piglets': [
  ("Weaner Piglets (Large White, 8 wks)", "/piglet", 38000, 4, "2 days", "Healthy 8-week Large White weaners, iron-injected and dewormed, from a closed herd.", {"Breed":"Large White","Age":"8 weeks","Weight":"12–15 kg"}, [("", 38000), ("— Landrace", 40000), ("— Duroc cross", 42000)]),
  ("Pregnant Gilt (Large White × Landrace)", "/head", 260000, 1, "3 days", "Confirmed pregnant F1 gilt, due in 6–8 weeks; first litter expected 10+.", {"Breed":"LW × Landrace","Status":"Pregnant"}, None),
  ("Market Pigs (90–100 kg, Live)", "/head", 210000, 2, "Same day", "Finished pigs at market weight, grain-fed with clean vaccination records.", {"Weight":"90–100 kg","Age":"6–7 months"}, None),
  ("Breeding Boar (Duroc)", "/head", 380000, 1, "3–5 days", "Proven Duroc boar for terminal crossing; improves growth rate and carcass quality.", {"Breed":"Duroc","Age":"14 months"}, None),
 ],
 'Rabbits': [
  ("New Zealand White Rabbits (Breeding Trio)", "/trio", 45000, 1, "2 days", "One buck and two does of proven New Zealand White stock, 5–6 months old.", {"Breed":"New Zealand White","Age":"5–6 months"}, [("", 45000), ("— Chinchilla", 48000), ("— Hyla", 60000)]),
  ("Weaner Rabbits (6 weeks)", "/kit", 6500, 4, "2 days", "Healthy weaned kits for grow-out or breeding stock.", {"Age":"6 weeks","Breeds":"Mixed"}, None),
  ("Rabbit Hutch (3-Tier Steel, 12 units)", "", 185000, 1, "5 days", "Galvanised wire hutch with 12 compartments, drop trays and feeders.", {"Units":"12","Material":"Galvanised wire"}, None),
  ("Rabbit Pellets (25 kg)", "/bag", 14500, 2, "24 hrs", "Balanced rabbit grower pellets with 16 % protein and high fibre.", {"Weight":"25 kg","Protein":"16 %"}, None),
 ],
 'Snails': [
  ("Giant African Snails (Jumbo Breeders, 50 pcs)", "/pack", 45000, 1, "2 days", "Archachatina marginata breeders 150 g+, sourced from farmed stock with high fecundity.", {"Species":"A. marginata","Weight":"150 g+","Count":"50"}, [("", 45000), ("— 100 pcs", 85000)]),
  ("Snail Hatchlings (500 pcs)", "/pack", 60000, 1, "3 days", "Healthy 2-week hatchlings for grow-out; 500 per pack with feeding guide.", {"Age":"2 weeks","Count":"500"}, None),
  ("Table-Size Snails (Basket of 100)", "/basket", 42000, 1, "Same day", "Cleaned table-size snails for restaurants and households.", {"Count":"100","Weight":"80–120 g each"}, None),
  ("Snail Pen Kit (Hutch Box, 6 Compartments)", "", 65000, 1, "5 days", "Treated-wood hutch with mosquito netting and moist soil trays for intensive snail farming.", {"Compartments":"6","Capacity":"300 snails"}, None),
 ],
 'Breeding Services': [
  ("Artificial Insemination — Cattle (per Cow)", "/cow", 25000, 1, "By schedule", "AI service using imported Friesian, Jersey or Brahman semen with heat synchronisation.", {"Semen":"Friesian / Jersey / Brahman","Includes":"Synchronisation"}, None),
  ("Pregnancy Diagnosis & Herd Check", "/visit", 35000, 1, "By schedule", "On-farm ultrasound pregnancy diagnosis and body condition scoring for up to 30 animals.", {"Animals":"Up to 30","Method":"Ultrasound"}, None),
  ("Boar Stud Service", "/service", 15000, 1, "By schedule", "Natural service or fresh semen from proven Duroc and Large White boars.", {"Breeds":"Duroc / Large White"}, None),
  ("Livestock Fattening Programme (90 days)", "/head", 120000, 5, "By schedule", "Feedlot fattening for rams and bulls ahead of festive markets; feed, housing and vet care included.", {"Duration":"90 days","Includes":"Feed + vet"}, None),
 ],
},
'fisheries': {
 'Fingerlings & Juveniles': [
  ("Catfish Fingerlings (3–5 cm)", "/pc", 45, 500, "24 hrs", "Fast-growing Clarias gariepinus fingerlings from selected broodstock; graded and packed with oxygen.", {"Species":"Clarias gariepinus","Size":"3–5 cm","Packing":"Oxygen bags"}, [("", 45), ("— 5,000+ pcs", 40)]),
  ("Catfish Juveniles (8–12 cm)", "/pc", 190, 200, "24 hrs", "Uniform juveniles, hardy and ready for grow-out; survival above 90 %.", {"Species":"Clarias gariepinus","Size":"8–12 cm"}, None),
  ("Tilapia Fingerlings (Sex-reversed, GIFT)", "/pc", 60, 500, "24 hrs", "All-male GIFT tilapia fingerlings for cage and pond culture; rapid growth.", {"Strain":"GIFT","Sex":"All male","Size":"3–5 cm"}, None),
  ("Heterobranchus Fingerlings (Hybrid Heteroclarias)", "/pc", 55, 500, "24 hrs", "Heteroclarias hybrid fingerlings with faster growth and larger final size.", {"Species":"Heteroclarias","Size":"4–6 cm"}, None),
 ],
 'Table-Size Fish': [
  ("Live Catfish (1–1.5 kg)", "/kg", 3200, 20, "Same day", "Pond-raised live catfish, harvested to order and delivered in aerated tanks.", {"Weight":"1–1.5 kg","Feeding":"Floating feed"}, [("", 3200), ("— 2 kg+", 3500)]),
  ("Fresh Tilapia (400–600 g)", "/kg", 3800, 10, "Same day", "Fresh pond tilapia on ice, cleaned on request.", {"Size":"400–600 g","Storage":"Iced"}, None),
  ("Catfish Broodstock (2–3 kg, Pair)", "/pair", 28000, 1, "2 days", "Selected male and female broodstock ready for induced spawning.", {"Weight":"2–3 kg each","Status":"Gravid"}, None),
 ],
 'Smoked & Dried Fish': [
  ("Oven-Smoked Catfish (1 kg pack)", "/kg", 9500, 2, "24 hrs", "Hygienically kiln-smoked catfish, low moisture, vacuum packed for export and retail.", {"Moisture":"< 12 %","Packaging":"Vacuum","Shelf life":"6 months"}, [("", 9500), ("— 5 kg carton", 46000)]),
  ("Dried Crayfish (Premium, 5 kg)", "/bag", 68000, 1, "24 hrs", "Sun-dried Oron crayfish, clean and sand-free.", {"Weight":"5 kg","Origin":"Oron"}, None),
  ("Smoked Tilapia (Carton of 20)", "/carton", 42000, 1, "24 hrs", "Whole smoked tilapia, evenly dried in a charcoal kiln.", {"Count":"20","Size":"300–400 g"}, None),
  ("Stockfish Heads (Bag)", "/bag", 55000, 1, "2 days", "Imported Norwegian stockfish heads, dry and sorted.", {"Weight":"~10 kg","Origin":"Norway"}, None),
 ],
 'Fish Feed': [
  ("Floating Catfish Feed 2 mm (15 kg)", "/bag", 21500, 5, "24 hrs", "Extruded floating feed, 45 % crude protein for fingerlings and juveniles.", {"Pellet":"2 mm","Protein":"45 %","Weight":"15 kg"}, [("", 21500), ("— 3 mm", 20800), ("— 4 mm", 20200), ("— 6 mm (40 %)", 19500), ("— 9 mm (38 %)", 19000)]),
  ("Sinking Catfish Feed 4 mm (25 kg)", "/bag", 24000, 5, "24 hrs", "Locally pelleted sinking feed for grow-out, 38 % protein.", {"Pellet":"4 mm","Protein":"38 %","Weight":"25 kg"}, None),
  ("Tilapia Floating Feed 3 mm (15 kg)", "/bag", 19800, 5, "24 hrs", "Balanced tilapia feed with 32 % protein and added vitamin C.", {"Pellet":"3 mm","Protein":"32 %"}, None),
  ("Fish Feed Starter Crumble (0.5–1 mm, 10 kg)", "/bag", 24500, 2, "24 hrs", "Micro-crumble for fry and early fingerlings, 50 % protein.", {"Size":"0.5–1 mm","Protein":"50 %"}, None),
 ],
 'Ponds & Tanks': [
  ("Tarpaulin Fish Pond (10 × 10 ft)", "", 95000, 1, "3 days", "Heavy-duty 1 mm tarpaulin pond with galvanised frame; holds 1,000 catfish to table size.", {"Size":"10 × 10 × 4 ft","Capacity":"1,000 fish","Frame":"Galvanised"}, [("", 95000), ("— 12 × 12 ft", 125000), ("— 15 × 15 ft", 185000)]),
  ("Fibreglass Tank (2,000 L)", "", 145000, 1, "5 days", "UV-stabilised fibreglass tank with bottom drain for hatcheries and nurseries.", {"Volume":"2,000 L","Drain":"50 mm"}, None),
  ("Plastic Fish Tank (1,500 L, Round)", "", 88000, 1, "3 days", "Food-grade polyethylene round tank with outlet fitting.", {"Volume":"1,500 L"}, None),
  ("Pond Liner HDPE (0.75 mm, per m²)", "/m²", 3200, 50, "3 days", "Durable HDPE geomembrane for earthen pond lining; 20-year life.", {"Thickness":"0.75 mm","Width":"6 m rolls"}, None),
 ],
 'Aerators & Pumps': [
  ("Paddle-Wheel Aerator (2 HP)", "", 385000, 1, "5–7 days", "Two-paddle floating aerator increasing dissolved oxygen for intensive ponds up to 0.5 ha.", {"Power":"2 HP","Coverage":"0.5 ha"}, [("", 385000), ("— 1 HP", 245000)]),
  ("Air Blower with Diffusers (RAS kit)", "/kit", 165000, 1, "5 days", "Ring blower, tubing and 20 air stones for recirculating tank systems.", {"Airflow":"120 m³/h","Stones":"20"}, None),
  ("Submersible Water Pump (1.5 HP)", "", 78000, 1, "2 days", "Stainless submersible pump for pond filling and water exchange.", {"Power":"1.5 HP","Head":"25 m"}, None),
  ("Dissolved Oxygen Meter (Portable)", "", 145000, 1, "3 days", "Digital DO and temperature meter with probe for daily water-quality checks.", {"Range":"0–20 mg/L"}, None),
 ],
 'Hatchery Services': [
  ("Catfish Induced Breeding Service", "/batch", 60000, 1, "By schedule", "On-site hormone-induced spawning, egg incubation and fry management for your broodstock.", {"Includes":"Hormone, incubation","Output":"50,000+ fry"}, None),
  ("Fish Farm Design & Setup", "/project", 350000, 1, "14 days", "Site assessment, pond layout, water system design and stocking plan.", {"Scope":"Up to 10 ponds"}, None),
  ("Water Quality Testing", "/test", 15000, 1, "2 days", "Laboratory analysis of pH, ammonia, nitrite, DO and hardness with recommendations.", {"Parameters":"7","Turnaround":"48 hrs"}, None),
  ("Fish Farming Practical Training (3 days)", "/person", 45000, 1, "Monthly", "Hands-on training covering hatchery, nursery and grow-out on a working farm.", {"Duration":"3 days","Certificate":"Yes"}, None),
 ],
},
'crops': {
 'Maize': [
  ("Yellow Maize (Dry, 100 kg)", "/bag", 68000, 5, "2–3 days", "Clean, well-dried yellow maize at 13 % moisture, aflatoxin-tested; ideal for feed mills.", {"Moisture":"≤ 13 %","Bag":"100 kg","Grade":"Feed grade"}, [("", 68000), ("— 30 tonnes (truckload)", 19800000)]),
  ("White Maize (Dry, 100 kg)", "/bag", 66000, 5, "2–3 days", "Premium white maize for milling and human consumption; sorted and bagged.", {"Moisture":"≤ 13 %","Bag":"100 kg"}, None),
  ("Fresh Sweet Corn (Bag of 100 cobs)", "/bag", 22000, 2, "Same day", "Tender sweet corn harvested at milk stage.", {"Count":"100 cobs","Harvest":"Same day"}, None),
  ("Popcorn Maize (50 kg)", "/bag", 52000, 2, "3 days", "High-expansion popcorn kernels, cleaned and graded.", {"Expansion":"> 40×","Bag":"50 kg"}, None),
 ],
 'Rice & Paddy': [
  ("Rice Paddy (FARO 44, 100 kg)", "/bag", 72000, 5, "3 days", "Dry paddy from Kebbi irrigated fields, 14 % moisture, low chaff.", {"Variety":"FARO 44","Moisture":"14 %","Bag":"100 kg"}, [("", 72000), ("— FARO 52", 73000)]),
  ("Parboiled Rice (Local, 50 kg)", "/bag", 78000, 2, "2 days", "Stone-free destoned parboiled long-grain rice, polished and sorted.", {"Bag":"50 kg","Grain":"Long","Stone-free":"Yes"}, [("", 78000), ("— 25 kg", 40000), ("— 10 kg", 16500)]),
  ("Ofada Rice (Unpolished, 25 kg)", "/bag", 55000, 1, "2 days", "Aromatic brown Ofada rice from Ogun State, hand-sorted.", {"Bag":"25 kg","Type":"Unpolished"}, None),
  ("Rice Bran (Animal Feed, 50 kg)", "/bag", 9500, 5, "2 days", "Fresh rice bran from our mill, a cost-effective energy source for livestock feed.", {"Bag":"50 kg","Protein":"12 %"}, None),
 ],
 'Soybean': [
  ("Soybean Grain (100 kg)", "/bag", 98000, 5, "3 days", "Clean TGX-variety soybeans, 12 % moisture, high oil and protein content.", {"Variety":"TGX 1448","Moisture":"12 %","Bag":"100 kg"}, [("", 98000), ("— 30 tonnes", 28500000)]),
  ("Full-Fat Soybean Meal (50 kg)", "/bag", 62000, 5, "2 days", "Properly toasted full-fat soya for poultry and fish rations.", {"Protein":"36 %","Fat":"18 %","Bag":"50 kg"}, None),
  ("Soybean Cake / Meal (50 kg)", "/bag", 54000, 5, "2 days", "Solvent-extracted soybean meal with 44 % protein.", {"Protein":"44 %","Bag":"50 kg"}, None),
 ],
 'Cassava & Tubers': [
  ("Fresh Cassava Roots (Tonne)", "/tonne", 95000, 1, "24 hrs", "Freshly harvested TME 419 cassava roots with high starch content, delivered within 24 hours of uprooting.", {"Variety":"TME 419","Starch":"25 %+","Harvest age":"12 months"}, None),
  ("Yam Tubers (Puna, 100 tubers)", "/100", 285000, 1, "2–3 days", "Large Puna yams from Benue, well cured and sorted; 2–3 kg each.", {"Variety":"Puna","Size":"2–3 kg","Count":"100"}, [("", 285000), ("— Abuja yam", 260000)]),
  ("Sweet Potato (Orange-Fleshed, 50 kg)", "/bag", 24000, 2, "2 days", "Vitamin-A-rich orange-fleshed sweet potatoes, freshly dug.", {"Variety":"OFSP","Bag":"50 kg"}, None),
  ("Irish Potatoes (Jos, 50 kg)", "/bag", 58000, 2, "2 days", "Plateau-grown Irish potatoes, graded medium-large, clean skin.", {"Origin":"Jos Plateau","Bag":"50 kg"}, None),
  ("Cocoyam (50 kg)", "/bag", 32000, 2, "2 days", "Fresh cocoyam corms, cleaned and bagged.", {"Bag":"50 kg"}, None),
 ],
 'Wheat & Sorghum': [
  ("Sorghum (Red, 100 kg)", "/bag", 58000, 5, "3 days", "Red guinea corn from Kano, dry and clean; for brewing and feed.", {"Type":"Red","Moisture":"12 %","Bag":"100 kg"}, [("", 58000), ("— white sorghum", 60000)]),
  ("Millet (Pearl, 100 kg)", "/bag", 62000, 5, "3 days", "Pearl millet grain, dry and sieved.", {"Type":"Pearl","Bag":"100 kg"}, None),
  ("Wheat Grain (Local, 100 kg)", "/bag", 88000, 5, "3 days", "Locally grown bread wheat from Kano-Jigawa irrigation schemes.", {"Variety":"Norman/Atilla","Bag":"100 kg"}, None),
  ("Wheat Offal (Bran, 50 kg)", "/bag", 11500, 5, "2 days", "Flour-mill wheat bran for livestock feed formulation.", {"Bag":"50 kg","Fibre":"10 %"}, None),
 ],
 'Beans & Legumes': [
  ("Brown Beans (Oloyin, 100 kg)", "/bag", 165000, 2, "2–3 days", "Sweet honey beans from Kebbi, weevil-free and sorted.", {"Variety":"Oloyin","Bag":"100 kg"}, [("", 165000), ("— white beans", 145000), ("— 50 kg", 84000)]),
  ("Groundnuts (Unshelled, 100 kg)", "/bag", 98000, 2, "3 days", "Dry unshelled groundnuts from Kano, aflatoxin-tested.", {"Type":"SAMNUT 24","Bag":"100 kg"}, [("", 98000), ("— shelled 50 kg", 96000)]),
  ("Bambara Nut (50 kg)", "/bag", 72000, 2, "3 days", "Clean bambara groundnut for okpa and snacks.", {"Bag":"50 kg"}, None),
  ("Pigeon Pea (50 kg)", "/bag", 48000, 2, "3 days", "Dried pigeon pea grain, a protein-rich legume.", {"Bag":"50 kg"}, None),
 ],
 'Sugarcane': [
  ("Sugarcane Stalks (Bundle of 50)", "/bundle", 18000, 5, "Same day", "Sweet chewing cane, freshly cut, 1.5–2 m stalks.", {"Count":"50","Variety":"Local chewing"}, None),
  ("Sugarcane Setts (Planting Material, 1,000)", "/1000", 65000, 1, "3 days", "Disease-free three-bud setts of improved industrial variety.", {"Variety":"CO 997","Buds":"3 per sett"}, None),
  ("Sugarcane Juice Extractor (Electric)", "", 285000, 1, "5 days", "Stainless-steel 3-roller cane juicer, 1.5 HP, for juice bars and processors.", {"Power":"1.5 HP","Output":"150 L/hr"}, None),
 ],
},
'seeds': {
 'Hybrid Maize Seed': [
  ("Hybrid Maize Seed SAMMAZ 15 (10 kg)", "/bag", 28000, 1, "2 days", "Certified drought-tolerant hybrid maize seed; 6–8 t/ha potential, 95 % germination.", {"Variety":"SAMMAZ 15","Germination":"95 %","Maturity":"105 days"}, [("", 28000), ("— SAMMAZ 52 (Pro-vitamin A)", 30000), ("— Oba Super 2", 32000), ("— 2 kg", 6500)]),
  ("Open-Pollinated Maize Seed (SUWAN 1, 10 kg)", "/bag", 16000, 1, "2 days", "Reliable OPV yellow maize seed; farmers may save seed for one season.", {"Variety":"SUWAN 1 SR","Germination":"90 %"}, None),
  ("Sweet Corn Seed (500 g)", "/pack", 22000, 1, "2 days", "Imported F1 supersweet corn seed for fresh-market growers.", {"Type":"F1 supersweet","Pack":"500 g"}, None),
 ],
 'Vegetable Seeds': [
  ("Tomato Seed F1 (Padma / Cobra, 10 g)", "/tin", 18500, 1, "2 days", "Heat-tolerant hybrid tomato with firm fruits and 40+ t/ha yield; resistant to TYLCV.", {"Type":"F1 hybrid","Pack":"10 g","Seeds":"~3,000"}, [("", 18500), ("— 50 g", 82000)]),
  ("Pepper Seed (Habanero F1, 10 g)", "/tin", 16000, 1, "2 days", "Hot pungent habanero (atarodo) hybrid with high yield.", {"Type":"F1","Pack":"10 g"}, [("", 16000), ("— Tatashe (bell)", 17500), ("— Shombo (cayenne)", 15000)]),
  ("Cucumber Seed F1 (Darina, 500 seeds)", "/tin", 12500, 1, "2 days", "Dark-green cucumber hybrid, early and prolific for open field.", {"Type":"F1","Seeds":"500"}, None),
  ("Watermelon Seed (Sugar Baby / Kaolack, 100 g)", "/pack", 14000, 1, "2 days", "Classic sweet round watermelon, 85 days to harvest.", {"Variety":"Sugar Baby","Pack":"100 g"}, [("", 14000), ("— Crimson Sweet F1", 22000)]),
  ("Okra Seed (Clemson Spineless, 500 g)", "/pack", 9500, 1, "2 days", "Spineless okra with tender pods; 50 days to first harvest.", {"Variety":"Clemson Spineless","Pack":"500 g"}, None),
  ("Ugu (Fluted Pumpkin) Seed Pods", "/pod", 3500, 5, "2 days", "Mature ugu pods with viable seeds for vegetable plots.", {"Seeds":"40–60 per pod"}, None),
 ],
 'Rice Seed': [
  ("Certified Rice Seed FARO 44 (25 kg)", "/bag", 42000, 1, "3 days", "Certified lowland rice seed with 90 % germination and high tillering.", {"Variety":"FARO 44 (SIPI)","Germination":"90 %","Ecology":"Lowland"}, [("", 42000), ("— FARO 52 (WITA 4)", 43000), ("— NERICA 8 (upland)", 45000)]),
  ("Foundation Rice Seed (FARO 66, 20 kg)", "/bag", 68000, 1, "3 days", "Foundation-class seed for seed producers and outgrower schemes.", {"Variety":"FARO 66","Class":"Foundation"}, None),
 ],
 'Seedlings & Nursery': [
  ("Tomato Seedlings (Tray of 200)", "/tray", 18000, 1, "2 days", "Healthy 4-week hybrid tomato seedlings raised in coco-peat trays, hardened for transplanting.", {"Age":"4 weeks","Count":"200"}, [("", 18000), ("— pepper", 17000), ("— cabbage", 15000)]),
  ("Cucumber Seedlings (Tray of 100)", "/tray", 12000, 1, "2 days", "Vigorous F1 cucumber seedlings ready for transplant.", {"Age":"2 weeks","Count":"100"}, None),
  ("Plantain Suckers (Improved PITA, 100 pcs)", "/100", 45000, 1, "3 days", "Disease-free plantain suckers; high bunch weight.", {"Variety":"PITA 14","Count":"100"}, None),
  ("Pineapple Suckers (Smooth Cayenne, 1,000)", "/1000", 180000, 1, "5 days", "Uniform suckers for commercial pineapple plantations.", {"Variety":"Smooth Cayenne","Count":"1,000"}, None),
 ],
 'Tree Seedlings': [
  ("Oil Palm Seedlings (Tenera, 12 months)", "/seedling", 2800, 50, "3–5 days", "NIFOR-sourced Tenera hybrid seedlings, ready for field planting; early bearing.", {"Variety":"Tenera","Age":"12 months","Bearing":"3 years"}, [("", 2800), ("— 500+", 2500)]),
  ("Cocoa Seedlings (CRIN Hybrid)", "/seedling", 850, 100, "3–5 days", "Improved CRIN hybrid cocoa seedlings, 4 months old, high pod count.", {"Source":"CRIN","Age":"4 months"}, None),
  ("Cashew Seedlings (Jumbo Nut)", "/seedling", 900, 50, "3 days", "Jumbo-nut cashew seedlings for export-grade nut production.", {"Variety":"Jumbo","Age":"4 months"}, None),
  ("Grafted Mango Seedlings (Kent / Keitt)", "/seedling", 4500, 10, "3 days", "Grafted mango seedlings bearing in 3 years; export varieties.", {"Variety":"Kent / Keitt","Type":"Grafted"}, [("", 4500), ("— citrus (sweet orange)", 3500), ("— avocado (Hass)", 5500)]),
  ("Moringa Seedlings", "/seedling", 600, 50, "3 days", "Fast-growing moringa for leaf and seed production.", {"Age":"3 months"}, None),
 ],
 'Organic Seeds': [
  ("Organic Vegetable Seed Bundle (10 varieties)", "/bundle", 24000, 1, "2 days", "Untreated open-pollinated seed: tomato, pepper, okra, amaranth, ugu, lettuce and more.", {"Varieties":"10","Treatment":"None"}, None),
  ("Amaranth (Tete) Seed, 1 kg", "/kg", 8500, 1, "2 days", "Local green amaranth seed with vigorous germination.", {"Pack":"1 kg"}, None),
  ("Sesame Seed (Planting Grade, 5 kg)", "/bag", 22000, 1, "3 days", "White sesame seed for planting, 95 % purity.", {"Variety":"E8","Pack":"5 kg"}, None),
 ],
},
'agrochem': {
 'Herbicides': [
  ("Glyphosate 360 SL (1 L)", "/L", 3800, 6, "24 hrs", "Non-selective systemic herbicide for land preparation and general weed control; NAFDAC registered.", {"Active":"Glyphosate 360 g/L","Pack":"1 L","Registration":"NAFDAC"}, [("", 3800), ("— 5 L", 17500), ("— 20 L", 66000)]),
  ("Atrazine 500 SC (1 L)", "/L", 4200, 6, "24 hrs", "Pre- and early post-emergence herbicide for maize and sugarcane.", {"Active":"Atrazine 500 g/L","Crops":"Maize, sugarcane"}, None),
  ("Paraquat Alternative — Glufosinate 150 SL (1 L)", "/L", 6800, 4, "24 hrs", "Fast-acting contact herbicide for burn-down before planting.", {"Active":"Glufosinate 150 g/L"}, None),
  ("Rice Herbicide (Propanil + 2,4-D, 1 L)", "/L", 5200, 6, "24 hrs", "Selective post-emergence control of grasses and broadleaves in rice.", {"Active":"Propanil 360 + 2,4-D 200","Crop":"Rice"}, None),
  ("Pendimethalin 400 EC (1 L)", "/L", 5600, 4, "24 hrs", "Pre-emergence residual herbicide for vegetables, groundnut and soybean.", {"Active":"Pendimethalin 400 g/L"}, None),
 ],
 'Insecticides': [
  ("Lambda-Cyhalothrin 2.5 EC (1 L)", "/L", 4500, 6, "24 hrs", "Broad-spectrum pyrethroid for caterpillars, aphids and beetles on vegetables and cowpea.", {"Active":"Lambda-cyhalothrin 25 g/L","Pack":"1 L"}, [("", 4500), ("— 250 ml", 1400)]),
  ("Emamectin Benzoate 5 % SG (100 g)", "/pack", 3200, 10, "24 hrs", "Highly effective against fall armyworm and pod borers.", {"Active":"Emamectin benzoate 5 %","Target":"Fall armyworm"}, None),
  ("Imidacloprid 200 SL (1 L)", "/L", 6200, 4, "24 hrs", "Systemic insecticide for whitefly, aphids and thrips; also seed treatment.", {"Active":"Imidacloprid 200 g/L"}, None),
  ("Cypermethrin 10 EC (1 L)", "/L", 3600, 6, "24 hrs", "Economical contact insecticide for field and stored-product pests.", {"Active":"Cypermethrin 100 g/L"}, None),
  ("Phostoxin Tablets (Grain Fumigant, Tin of 100)", "/tin", 18500, 1, "24 hrs", "Aluminium phosphide fumigant for stored grain; licensed applicators only.", {"Active":"Aluminium phosphide 56 %","Tablets":"100"}, None),
 ],
 'Fungicides': [
  ("Mancozeb 80 WP (1 kg)", "/kg", 4800, 6, "24 hrs", "Protectant fungicide for early/late blight in tomato and potato, and black pod in cocoa.", {"Active":"Mancozeb 80 %","Pack":"1 kg"}, [("", 4800), ("— 500 g", 2600)]),
  ("Copper Oxychloride 50 WP (1 kg)", "/kg", 5200, 6, "24 hrs", "Copper fungicide/bactericide for cocoa black pod, citrus and vegetables.", {"Active":"Copper oxychloride 50 %"}, None),
  ("Metalaxyl + Mancozeb 72 WP (1 kg)", "/kg", 7800, 4, "24 hrs", "Systemic and contact action against downy mildew and late blight.", {"Active":"Metalaxyl 8 % + Mancozeb 64 %"}, None),
  ("Tebuconazole 250 EC (1 L)", "/L", 9500, 4, "24 hrs", "Systemic triazole for rusts, leaf spots and Sigatoka.", {"Active":"Tebuconazole 250 g/L"}, None),
 ],
 'Growth Regulators': [
  ("Gibberellic Acid 10 % (100 g)", "/pack", 12500, 2, "24 hrs", "Plant growth regulator to improve fruit set and size in grapes, citrus and vegetables.", {"Active":"GA3 10 %"}, None),
  ("Seaweed Extract Biostimulant (1 L)", "/L", 6500, 4, "24 hrs", "Natural kelp extract boosting root growth and stress tolerance.", {"Source":"Ascophyllum nodosum"}, [("", 6500), ("— 5 L", 29000)]),
  ("Amino Acid Growth Booster (1 L)", "/L", 7200, 4, "24 hrs", "Foliar amino-acid complex for rapid recovery after transplanting and stress.", {"Amino acids":"18 %"}, None),
  ("Rooting Hormone Powder (100 g)", "/pack", 4500, 5, "24 hrs", "IBA rooting powder for cuttings of cocoa, cashew and ornamentals.", {"Active":"IBA 0.3 %"}, None),
 ],
 'Bio-Pesticides': [
  ("Neem Oil Concentrate (1 L)", "/L", 6800, 4, "24 hrs", "Cold-pressed azadirachtin-rich neem oil; organic control of sucking pests.", {"Azadirachtin":"1,500 ppm","Organic":"Yes"}, [("", 6800), ("— 5 L", 31000)]),
  ("Bacillus thuringiensis (Bt) WP, 500 g", "/pack", 8500, 4, "24 hrs", "Biological caterpillar control safe for beneficial insects.", {"Strain":"Bt kurstaki"}, None),
  ("Beauveria bassiana Bio-insecticide (1 kg)", "/kg", 9800, 2, "24 hrs", "Entomopathogenic fungus for whitefly, thrips and weevils.", {"Spores":"1×10⁸ cfu/g"}, None),
  ("Trichoderma Soil Bio-fungicide (1 kg)", "/kg", 7500, 4, "24 hrs", "Root-zone antagonist against Fusarium, Pythium and damping-off.", {"Strain":"T. harzianum"}, None),
  ("Yellow Sticky Traps (Pack of 20)", "/pack", 6000, 3, "24 hrs", "Insect monitoring and mass trapping for whitefly and leaf miners.", {"Size":"20 × 25 cm","Count":"20"}, None),
 ],
 'Sprayers': [
  ("Knapsack Sprayer 16 L (Manual)", "", 18500, 1, "24 hrs", "Robust lever-operated knapsack with brass lance and adjustable nozzle.", {"Capacity":"16 L","Pump":"Piston"}, [("", 18500), ("— 20 L", 21000)]),
  ("Battery Knapsack Sprayer 16 L", "", 42000, 1, "24 hrs", "12 V rechargeable sprayer, 6–8 hours per charge, 3 nozzle types.", {"Capacity":"16 L","Battery":"12 V 8 Ah"}, [("", 42000), ("— 20 L", 48000)]),
  ("Motorised Mist Blower (14 L)", "", 165000, 1, "3 days", "Two-stroke mist blower for orchards and plantations, 12 m horizontal reach.", {"Engine":"2-stroke 42 cc","Reach":"12 m"}, None),
  ("Tractor-Mounted Boom Sprayer (600 L)", "", 2400000, 1, "10 days", "PTO-driven boom sprayer, 12 m hydraulic boom, for large arable fields.", {"Tank":"600 L","Boom":"12 m"}, None),
  ("Sprayer Nozzle Set (Fan / Cone / Flood, 12 pcs)", "/set", 6500, 2, "24 hrs", "Assorted replacement nozzles for knapsack and boom sprayers.", {"Count":"12"}, None),
 ],
},
}
