# Catalogue spec, part C — storage, irrigation, greenhouse, agtech, logistics, transport, advisory, services
SPEC_C = {
'storage': {
 'Grain Silos': [
  ("Galvanised Steel Silo (50 t)", "", 8500000, 1, "45 days", "Flat-bottom corrugated steel silo with aeration floor, temperature cables and loading auger; installed on your site.", {"Capacity":"50 t","Aeration":"Yes","Installation":"Included"}, [("", 8500000), ("— 100 t", 14500000), ("— 500 t", 52000000)]),
  ("Hopper-Bottom Feed Silo (10 t)", "", 3200000, 1, "30 days", "Self-emptying feed silo for poultry and pig farms with boot and auger.", {"Capacity":"10 t"}, None),
  ("Plastic Grain Silo (1 t)", "", 185000, 1, "5 days", "Household/smallholder hermetic plastic silo with sealed lid.", {"Capacity":"1 t"}, [("", 185000), ("— 500 kg", 110000)]),
  ("Metal Silo (Artisanal, 2 t)", "", 320000, 1, "10 days", "Locally fabricated airtight metal silo for maize and cowpea.", {"Capacity":"2 t"}, None),
 ],
 'Warehousing': [
  ("Warehouse Space — Lagos (per Pallet per Month)", "/pallet-month", 8500, 5, "Same day", "Secure, pest-controlled dry warehouse near Apapa with 24-hour security and inventory reports.", {"Location":"Lagos","Security":"24/7","Insurance":"Included"}, [("", 8500), ("— Kano", 5500), ("— Abuja", 7000), ("— Onitsha", 6000)]),
  ("Bulk Grain Storage (per Tonne per Month)", "/t-month", 3500, 20, "Same day", "Fumigated grain warehouse with weighbridge and receipt system.", {"Min":"20 t","Weighbridge":"Yes"}, None),
  ("Warehouse Receipt Financing Support", "/lot", 45000, 1, "5 days", "Grading, certification and collateral-manager setup for stored commodities.", {"Commodities":"Maize, paddy, soybean"}, None),
  ("Pallets (Plastic, Heavy Duty, Pack of 10)", "/pack", 185000, 1, "3 days", "Rackable plastic pallets 1.2 × 1 m, 1,500 kg dynamic load.", {"Size":"1.2 × 1 m","Count":"10"}, None),
 ],
 'Cold Storage': [
  ("Cold Storage — Chilled (per Pallet per Week)", "/pallet-week", 14000, 1, "Same day", "Temperature-logged chilled storage for fruits, vegetables and dairy.", {"Temp":"2–8 °C","Logging":"Yes"}, [("", 14000), ("— frozen (-18 °C)", 18000)]),
  ("Ripening Room Service (Banana / Mango)", "/tonne", 25000, 2, "Same day", "Ethylene-controlled ripening chambers.", {"Crops":"Banana, mango, plantain"}, None),
  ("Onion & Potato Ventilated Store (100 t)", "", 6500000, 1, "45 days", "Naturally ventilated curing and storage shed with fans.", {"Capacity":"100 t"}, None),
  ("Ice Blocks (per 25 kg Block)", "/block", 1500, 20, "Same day", "Clean ice for fish and produce transport.", {"Weight":"25 kg"}, None),
 ],
 'Hermetic Bags': [
  ("PICS Hermetic Bags (100 kg, Pack of 10)", "/pack", 28000, 2, "24 hrs", "Triple-layer hermetic bags that stop weevils without chemicals; keeps grain safe for 12+ months.", {"Capacity":"100 kg","Layers":"3","Count":"10"}, [("", 28000), ("— 50 kg", 21000), ("— 100 pcs", 260000)]),
  ("GrainPro Cocoon (5 t)", "", 850000, 1, "10 days", "Sealable gas-tight cocoon for bulk bagged storage.", {"Capacity":"5 t"}, None),
  ("Polypropylene Sacks 100 kg (Bale of 100)", "/bale", 45000, 2, "24 hrs", "Woven PP sacks with liner.", {"Count":"100"}, [("", 45000), ("— 50 kg", 30000)]),
  ("Jute Bags (Cocoa Grade, Bale of 50)", "/bale", 72000, 1, "3 days", "Food-grade hydrocarbon-free jute bags for cocoa and coffee export.", {"Count":"50"}, None),
 ],
 'Storage Rental': [
  ("Farm Storage Shed Rental (200 m²)", "/month", 150000, 1, "3 days", "Covered shed with concrete floor for equipment and produce.", {"Area":"200 m²"}, None),
  ("Mobile Container Store (20 ft)", "/month", 65000, 1, "5 days", "Delivered 20 ft container for on-farm secure storage.", {"Size":"20 ft"}, None),
  ("Tarpaulins (Heavy-Duty, 12 × 18 m)", "", 85000, 1, "24 hrs", "Waterproof PVC tarp for grain heaps and drying floors.", {"Size":"12 × 18 m"}, [("", 85000), ("— 6 × 9 m", 24000)]),
  ("Stackable Plastic Crates (Pack of 20)", "/pack", 68000, 1, "2 days", "Ventilated crates 60 × 40 × 30 cm for tomato and fruit.", {"Count":"20"}, None),
 ],
 'Pest Control': [
  ("Warehouse Fumigation Service (per 100 m²)", "/100m²", 45000, 1, "By schedule", "Licensed phosphine fumigation with gas-tight sheeting and clearance certificate.", {"Method":"Phosphine","Certificate":"Yes"}, None),
  ("Rodent Control Programme (Monthly)", "/month", 35000, 1, "By schedule", "Bait stations, traps and monitoring for stores and poultry houses.", {"Visits":"2 / month"}, None),
  ("Grain Protectant Dust (Actellic, 1 kg)", "/kg", 6500, 5, "24 hrs", "Pirimiphos-methyl dust for admixture with stored grain.", {"Active":"Pirimiphos-methyl 2 %"}, None),
  ("Insect Monitoring Traps (Stored Product, 10 pcs)", "/pack", 12000, 2, "24 hrs", "Pheromone traps for weevils and moths.", {"Count":"10"}, None),
 ],
},
'irrigation': {
 'Drip Kits': [
  ("Drip Irrigation Kit (1 acre)", "/kit", 385000, 1, "5 days", "Complete kit: 16 mm drip lines at 30 cm spacing, sub-main, filter, venturi injector and fittings.", {"Area":"1 acre","Emitter":"1.6 L/h @ 30 cm","Filter":"Screen 120 mesh"}, [("", 385000), ("— ¼ acre", 120000), ("— 1 hectare", 880000)]),
  ("Drip Tape (16 mm, 1,000 m Roll)", "/roll", 48000, 2, "3 days", "Thin-wall drip tape with 30 cm emitters.", {"Length":"1,000 m","Wall":"0.2 mm"}, [("", 48000), ("— 20 cm spacing", 50000)]),
  ("Greenhouse Drip Kit (8 × 24 m)", "/kit", 95000, 1, "3 days", "Pressure-compensating drip kit for tunnels with tank connector.", {"Beds":"6"}, None),
  ("Venturi Fertigation Injector (1\")", "", 18500, 1, "24 hrs", "Simple fertilizer injection for drip systems.", {"Size":"1 in"}, None),
 ],
 'Sprinklers': [
  ("Rain Gun Sprinkler (1.5\", 30 m Radius)", "", 85000, 1, "3 days", "Big-gun sprinkler for pasture, maize and vegetables.", {"Radius":"30 m","Inlet":"1.5 in"}, [("", 85000), ("— 2 in, 45 m", 165000)]),
  ("Impact Sprinkler Kit (10 Heads + Risers)", "/kit", 65000, 1, "3 days", "Brass impact sprinklers on 1 m risers with quick couplings.", {"Heads":"10","Radius":"12 m"}, None),
  ("Micro-Sprinklers (Pack of 100)", "/pack", 28000, 1, "24 hrs", "Low-flow micro-jets for nurseries and orchards.", {"Count":"100","Flow":"40 L/h"}, None),
  ("Hose-Reel Irrigator (200 m)", "", 4800000, 1, "30 days", "Travelling irrigator for 10–20 ha fields.", {"Hose":"200 m"}, None),
 ],
 'Center Pivots': [
  ("Center Pivot Irrigation System (50 ha)", "", 95000000, 1, "90 days", "Galvanised 7-span pivot with sprinkler package, control panel and installation.", {"Area":"50 ha","Spans":"7"}, [("", 95000000), ("— 20 ha", 48000000)]),
  ("Linear Move Irrigator (30 ha)", "", 78000000, 1, "90 days", "Linear-move machine for rectangular fields.", {"Area":"30 ha"}, None),
  ("Pivot Servicing & Parts", "/visit", 150000, 1, "By schedule", "Gearbox, tyre and sprinkler servicing by certified technicians.", {"Coverage":"Nationwide"}, None),
 ],
 'Boreholes': [
  ("Borehole Drilling (Up to 100 m, Complete)", "/borehole", 1850000, 1, "7–14 days", "Geophysical survey, drilling, casing, gravel pack, test pumping and submersible pump installation.", {"Depth":"Up to 100 m","Includes":"Survey + pump"}, [("", 1850000), ("— up to 60 m", 1250000), ("— industrial 150 m (6\")", 4800000)]),
  ("Geophysical Water Survey", "/site", 85000, 1, "3 days", "Electrical resistivity survey to site your borehole.", {"Method":"VES"}, None),
  ("Overhead Water Tank (10,000 L) + Stanchion", "", 1450000, 1, "10 days", "PE tank on 6 m steel tower.", {"Volume":"10,000 L"}, None),
  ("Hand Pump (India Mark II)", "", 385000, 1, "7 days", "Community hand pump for shallow boreholes.", {"Depth":"Up to 45 m"}, None),
 ],
 'Solar Pumps': [
  ("Solar Water Pump System (1 HP, Complete)", "/system", 850000, 1, "5 days", "DC submersible pump with 1.2 kW panel array, controller and 6 m mounting; pumps 25 m³/day.", {"Power":"1 HP","Panels":"1.2 kW","Output":"25 m³/day"}, [("", 850000), ("— 2 HP", 1450000), ("— 5 HP", 3200000)]),
  ("Solar Surface Pump Kit (Small Farm)", "/kit", 320000, 1, "3 days", "Portable solar pump for rivers and shallow wells.", {"Flow":"3 m³/h"}, None),
  ("Solar Pump Controller (MPPT, 2.2 kW)", "", 185000, 1, "3 days", "Replacement MPPT inverter controller.", {"Power":"2.2 kW"}, None),
 ],
 'Pipes & Fittings': [
  ("HDPE Pipe 2\" PN10 (100 m Roll)", "/roll", 145000, 1, "3 days", "UV-stabilised HDPE pipe for mainlines.", {"Size":"2 in","Pressure":"PN10"}, [("", 145000), ("— 1½ in", 98000), ("— 3 in", 285000)]),
  ("Lay-Flat Hose 3\" (100 m)", "/roll", 68000, 1, "3 days", "Flexible PVC lay-flat for pump discharge.", {"Size":"3 in"}, None),
  ("PVC Pipes & Fittings Bundle (1 acre)", "/bundle", 220000, 1, "3 days", "Assorted uPVC pipes, elbows, tees and valves.", {"Area":"1 acre"}, None),
  ("Ball Valves & Filters Set (2\")", "/set", 42000, 1, "24 hrs", "Brass ball valves and disc filter.", {"Size":"2 in"}, None),
 ],
},
'greenhouse': {
 'Tunnel Greenhouses': [
  ("Tunnel Greenhouse 8 × 24 m (Complete)", "", 2650000, 1, "14 days", "Galvanised frame, 200-micron UV film, insect net sides, drip system and installation; grows 1,200 tomato plants.", {"Size":"8 × 24 m","Film":"200 µm UV","Plants":"~1,200"}, [("", 2650000), ("— 8 × 30 m", 3200000), ("— 10 × 40 m", 5400000)]),
  ("Multi-Span Greenhouse (1,000 m²)", "", 18500000, 1, "45 days", "Commercial multi-span with roll-up vents and fertigation.", {"Area":"1,000 m²"}, None),
  ("Greenhouse Film 200 µm (8 × 50 m)", "/roll", 285000, 1, "3 days", "UV-stabilised polythene, 3-season life.", {"Size":"8 × 50 m"}, None),
  ("Greenhouse Repair & Re-covering Service", "/unit", 350000, 1, "7 days", "Replace film, nets and doors on existing tunnels.", {"Size":"Up to 8 × 30 m"}, None),
 ],
 'Hydroponic Kits': [
  ("NFT Hydroponic System (200 plants)", "/system", 485000, 1, "7 days", "Food-grade NFT channels, reservoir, pump and nutrient starter pack for lettuce and herbs.", {"Plants":"200","System":"NFT"}, [("", 485000), ("— 500 plants", 980000)]),
  ("Dutch Bucket Kit (Tomato / Pepper, 20 Buckets)", "/kit", 165000, 1, "5 days", "Bato buckets with drip and drain lines for fruiting crops.", {"Buckets":"20"}, None),
  ("Hydroponic Nutrient A+B (5 L each)", "/set", 28000, 1, "24 hrs", "Two-part complete nutrient for leafy greens.", {"Volume":"2 × 5 L"}, None),
  ("Coco Peat Blocks (5 kg, Pack of 10)", "/pack", 32000, 1, "3 days", "Washed, buffered coco peat for soilless media.", {"Count":"10","Expands":"70 L each"}, None),
  ("pH & EC Meter Set", "/set", 24000, 1, "24 hrs", "Digital pen meters for nutrient management.", {"Pieces":"2"}, None),
 ],
 'Shade Nets': [
  ("Shade Net 50 % (4 × 50 m)", "/roll", 68000, 1, "3 days", "UV-stabilised HDPE shade net for nurseries and vegetables.", {"Shade":"50 %","Size":"4 × 50 m"}, [("", 68000), ("— 70 %", 78000), ("— 35 %", 62000)]),
  ("Insect Net 40 Mesh (3 × 50 m)", "/roll", 85000, 1, "3 days", "Fine anti-whitefly netting for greenhouse sides.", {"Mesh":"40","Size":"3 × 50 m"}, None),
  ("Shade House Structure (10 × 20 m)", "", 950000, 1, "10 days", "Steel-post shade house with 50 % net and door.", {"Size":"10 × 20 m"}, None),
  ("Bird Netting (10 × 20 m)", "", 42000, 1, "3 days", "Protects fruit trees and fish ponds from birds.", {"Size":"10 × 20 m"}, None),
 ],
 'Grow Lights': [
  ("LED Grow Light Bar (120 W, Full Spectrum)", "", 65000, 2, "3 days", "Full-spectrum LED for seedlings and indoor greens; 50,000-hour life.", {"Power":"120 W","Spectrum":"Full"}, [("", 65000), ("— 240 W", 118000)]),
  ("Grow Light Kit for Seedling Rack (4 Tiers)", "/kit", 285000, 1, "5 days", "Four-tier rack with LED bars, timer and trays.", {"Tiers":"4"}, None),
  ("Poultry LED Lighting (Dimmable, 20 lamps)", "/pack", 96000, 1, "3 days", "Warm-white dimmable lamps for layer houses.", {"Count":"20","Power":"9 W"}, None),
 ],
 'Vertical Farming': [
  ("Vertical Farm Tower (Aeroponic, 44 plants)", "", 185000, 1, "5 days", "Stackable aeroponic tower with pump and timer for balconies and rooftops.", {"Plants":"44","Footprint":"0.6 m²"}, [("", 185000), ("— pack of 5", 850000)]),
  ("Container Farm (40 ft, Turnkey)", "", 65000000, 1, "90 days", "Climate-controlled shipping-container farm producing 4,000 lettuce heads per month.", {"Output":"4,000 heads/month"}, None),
  ("Vertical Rack System (3 × 2 m, 5 Tiers)", "", 850000, 1, "14 days", "Steel racks with LED and ebb-flow trays.", {"Tiers":"5"}, None),
  ("Microgreens Starter Kit", "/kit", 45000, 1, "3 days", "Trays, media, seeds and guide for microgreens business.", {"Trays":"20"}, None),
 ],
 'Nursery Trays': [
  ("Seedling Trays 128-Cell (Pack of 50)", "/pack", 42000, 1, "24 hrs", "Reusable PS trays for vegetable nurseries.", {"Cells":"128","Count":"50"}, [("", 42000), ("— 72-cell", 40000), ("— 200-cell", 45000)]),
  ("Nursery Poly Bags 5 × 8\" (1,000 pcs)", "/pack", 18000, 2, "24 hrs", "Black perforated bags for tree and oil-palm seedlings.", {"Size":"5 × 8 in","Count":"1,000"}, [("", 18000), ("— 8 × 12 in", 32000)]),
  ("Peat Pellets / Jiffy (1,000 pcs)", "/pack", 65000, 1, "3 days", "Compressed peat pellets for fast germination.", {"Count":"1,000"}, None),
  ("Nursery Benches (Galvanised, 1.2 × 3 m)", "", 85000, 2, "5 days", "Raised mesh benches for trays and pots.", {"Size":"1.2 × 3 m"}, None),
 ],
},
'agtech': {
 'Spraying Drones': [
  ("Agricultural Spraying Drone (30 L)", "", 28500000, 1, "30 days", "RTK-enabled 30 L spray drone covering 16 ha/hour with radar terrain following, two batteries and charger; pilot training included.", {"Tank":"30 L","Coverage":"16 ha/hr","Training":"Included"}, [("", 28500000), ("— 10 L", 12500000), ("— 50 L", 42000000)]),
  ("Drone Spraying Service (per Hectare)", "/ha", 18000, 5, "By schedule", "Licensed drone pilots spray herbicide, insecticide or foliar fertilizer.", {"Min":"5 ha","Coverage":"Nationwide"}, None),
  ("Crop-Scouting Drone (Multispectral)", "", 9800000, 1, "21 days", "Multispectral mapping drone producing NDVI health maps.", {"Sensor":"5-band multispectral","Flight":"45 min"}, None),
  ("Drone Mapping Service (per 100 ha)", "/100ha", 250000, 1, "By schedule", "Orthomosaic and NDVI maps with agronomist interpretation.", {"Output":"Maps + report"}, None),
 ],
 'Soil Sensors': [
  ("Soil Moisture Sensor Kit (IoT, 4 Probes)", "/kit", 285000, 1, "7 days", "LoRa soil probes with gateway and dashboard for irrigation scheduling.", {"Probes":"4","Depth":"30 / 60 cm","Connectivity":"LoRa + GSM"}, None),
  ("Handheld Soil Tester (pH, Moisture, NPK)", "", 68000, 1, "3 days", "Digital 4-in-1 probe with Bluetooth app.", {"Parameters":"pH, moisture, N-P-K"}, None),
  ("Tensiometer Set (3 Depths)", "/set", 45000, 1, "5 days", "Field tensiometers for drip scheduling.", {"Depths":"20/40/60 cm"}, None),
  ("Automated Irrigation Controller (8 Zones)", "", 185000, 1, "5 days", "Wi-Fi controller with weather-based scheduling.", {"Zones":"8"}, None),
 ],
 'Farm Management Software': [
  ("AgricWorld Farm Manager (Annual Licence)", "/year", 120000, 1, "Instant", "Records, inventory, payroll, sales and profit reports for crop and livestock farms; works offline on mobile.", {"Users":"5","Offline":"Yes","Support":"WhatsApp"}, [("", 120000), ("— enterprise (unlimited users)", 480000)]),
  ("Poultry Farm App (Flock Records, Annual)", "/year", 60000, 1, "Instant", "Mortality, feed, egg and medication tracking with alerts.", {"Flocks":"Unlimited"}, None),
  ("Farm Accounting Setup & Training", "/farm", 150000, 1, "5 days", "Chart of accounts, templates and two training sessions.", {"Sessions":"2"}, None),
  ("Traceability & QR Labelling System", "/farm", 250000, 1, "10 days", "Batch traceability with printable QR labels for export compliance.", {"Includes":"Printer + software"}, None),
 ],
 'Weather Stations': [
  ("Automatic Weather Station (Solar, GSM)", "", 1250000, 1, "14 days", "Rain, temperature, humidity, wind and solar radiation with SMS alerts and web dashboard.", {"Sensors":"6","Power":"Solar","Data":"GSM"}, None),
  ("Rain Gauge & Min-Max Thermometer Set", "/set", 18500, 1, "3 days", "Manual weather kit for farm records.", {"Pieces":"2"}, None),
  ("Agro-Weather Advisory Subscription (SMS)", "/season", 8000, 1, "Instant", "Localised 7-day forecasts and planting advisories by SMS.", {"Frequency":"Daily"}, None),
 ],
 'Solar Energy': [
  ("Solar Mini-Grid for Farm Cluster (30 kW)", "", 48000000, 1, "90 days", "Containerised solar mini-grid powering cold rooms, mills and irrigation.", {"Power":"30 kW","Storage":"120 kWh"}, None),
  ("Solar Dryer + Cold Room Combo (Market Cluster)", "", 22000000, 1, "60 days", "Shared post-harvest hub for cooperatives.", {"Cold room":"10 ft","Dryer":"200 kg"}, None),
  ("Solar Generator (Portable, 2 kWh)", "", 850000, 1, "5 days", "Portable power station with 400 W panels for field equipment.", {"Capacity":"2 kWh"}, None),
  ("Solar Panels 550 W Mono (Pack of 10)", "/pack", 1650000, 1, "5 days", "Tier-1 monocrystalline panels, 25-year warranty.", {"Power":"550 W","Count":"10"}, None),
 ],
 'GPS & Mapping': [
  ("Farm Boundary Survey & Mapping (per 10 ha)", "/10ha", 85000, 1, "3 days", "GNSS survey with certified coordinates and layout plan.", {"Accuracy":"±10 cm"}, None),
  ("Tractor GPS Guidance Kit", "", 1850000, 1, "14 days", "Light-bar guidance with 20 cm accuracy for planting and spraying.", {"Accuracy":"20 cm"}, None),
  ("Handheld GPS (Farm Grade)", "", 185000, 1, "3 days", "Rugged handheld receiver for area measurement.", {"Battery":"16 hrs"}, None),
  ("Satellite Crop Monitoring (per 100 ha per Season)", "/100ha", 150000, 1, "Instant", "Weekly satellite NDVI and moisture alerts.", {"Frequency":"Weekly"}, None),
 ],
},
'logistics': {
 'Cold-Chain Delivery': [
  ("Refrigerated Van Delivery — Lagos (per Trip)", "/trip", 45000, 1, "Same day", "3-tonne reefer van for fresh produce, dairy and fish within Lagos; temperature log provided.", {"Capacity":"3 t","Temp":"-18 to +8 °C","Coverage":"Lagos"}, [("", 45000), ("— Lagos → Ibadan", 95000), ("— Lagos → Abuja", 420000)]),
  ("Cold-Chain Groupage (per Pallet, Lagos–Abuja)", "/pallet", 85000, 1, "48 hrs", "Shared reefer truck departing twice weekly.", {"Departures":"Tue / Fri"}, None),
  ("Insulated Boxes with Ice Packs (Pack of 10)", "/pack", 65000, 1, "2 days", "Reusable EPS boxes for fish and vaccine delivery.", {"Volume":"40 L","Count":"10"}, None),
  ("Vaccine Cold-Chain Courier", "/shipment", 15000, 1, "24 hrs", "Temperature-monitored courier for vaccines and semen.", {"Monitoring":"Data logger"}, None),
 ],
 'Export Handling': [
  ("Export Consolidation & Sea Freight (20 ft, Apapa → Rotterdam)", "/container", 4200000, 1, "30 days", "Container, port handling, documentation and ocean freight for agro-commodities.", {"Container":"20 ft","Transit":"25–30 days"}, [("", 4200000), ("— 40 ft", 6200000)]),
  ("Air Freight Fresh Produce (per kg, Lagos → London)", "/kg", 2800, 200, "48 hrs", "Perishables air freight with pre-cooling and cargo booking.", {"Min":"200 kg"}, None),
  ("Export Documentation Package", "/shipment", 180000, 1, "5 days", "NEPC registration, phytosanitary, certificate of origin, SONCAP and bill of lading.", {"Documents":"5+"}, None),
  ("Pre-Shipment Inspection & Fumigation", "/container", 120000, 1, "3 days", "SGS-type inspection and container fumigation certificate.", {"Certificate":"Yes"}, None),
 ],
 'Last-Mile Delivery': [
  ("Motorbike Delivery — Farm Produce (Lagos)", "/delivery", 3500, 1, "Same day", "Insulated-box dispatch riders for eggs, vegetables and meat within Lagos.", {"Max":"25 kg","Coverage":"Lagos"}, None),
  ("Tricycle (Keke) Cargo Delivery", "/trip", 8500, 1, "Same day", "Cargo tricycle for crates and sacks up to 300 kg.", {"Max":"300 kg"}, None),
  ("Mini-Van Delivery (1 t, Intra-city)", "/trip", 25000, 1, "Same day", "Covered 1-tonne van for market deliveries.", {"Max":"1 t"}, None),
  ("Subscription Delivery for Farms (Monthly, 20 Drops)", "/month", 55000, 1, "Instant", "Scheduled deliveries to retailers and restaurants.", {"Drops":"20"}, None),
 ],
 'Freight Forwarding': [
  ("Full-Truck Freight (30 t, Kano → Lagos)", "/truck", 1350000, 1, "3 days", "Covered 30-tonne truck with GPS tracking and goods-in-transit insurance.", {"Capacity":"30 t","Insurance":"GIT"}, [("", 1350000), ("— Lagos → Kano", 1250000), ("— Jos → Lagos", 1150000), ("— Makurdi → Lagos", 950000)]),
  ("Less-than-Truckload Groupage (per Tonne)", "/tonne", 55000, 1, "5 days", "Shared trucks on major corridors weekly.", {"Corridors":"Lagos–Kano–Abuja–PH"}, None),
  ("Rail Freight Booking (Container, Lagos–Ibadan)", "/container", 350000, 1, "3 days", "Booking and handling on the standard-gauge line.", {"Container":"20 ft"}, None),
  ("Customs Clearing (Import, Apapa)", "/container", 450000, 1, "7 days", "Duty assessment, PAAR and clearing for agro-machinery and inputs.", {"Includes":"Agency fee"}, None),
 ],
 'Customs & Docs': [
  ("NEPC Exporter Registration Support", "/company", 85000, 1, "10 days", "End-to-end registration with the Nigerian Export Promotion Council.", {"Turnaround":"10 days"}, None),
  ("Phytosanitary Certificate Processing", "/shipment", 45000, 1, "3 days", "NAQS inspection booking and certificate.", {"Agency":"NAQS"}, None),
  ("NAFDAC Product Registration (Food)", "/product", 650000, 1, "90 days", "Dossier, lab tests and facility inspection support.", {"Scope":"One product"}, None),
  ("Certificate of Origin & Form NXP", "/shipment", 35000, 1, "3 days", "Chamber of Commerce CoO and bank NXP processing.", {"Documents":"2"}, None),
 ],
 'Packaging': [
  ("Egg Crates (Paper Pulp, 30-Egg, Bundle of 140)", "/bundle", 42000, 1, "24 hrs", "Moulded pulp trays for safe egg transport.", {"Count":"140"}, None),
  ("Fruit Cartons (Printed, 5 kg, Pack of 100)", "/pack", 85000, 1, "5 days", "Corrugated ventilated cartons with your branding.", {"Count":"100","Print":"2 colours"}, None),
  ("Mesh Bags for Onions (25 kg, 1,000 pcs)", "/pack", 65000, 1, "3 days", "Woven leno mesh bags.", {"Count":"1,000"}, None),
  ("Vacuum Pouches (Food Grade, 1,000 pcs)", "/pack", 38000, 1, "3 days", "Clear nylon/PE pouches for smoked fish and kernels.", {"Size":"20 × 30 cm"}, None),
  ("Branded Rice Bags (5 kg, 1,000 pcs)", "/pack", 145000, 1, "10 days", "BOPP laminated woven bags with your logo.", {"Count":"1,000"}, None),
 ],
},
'transport': {
 'Truck Haulage': [
  ("Truck Haulage 10 t (Intra-state, per Trip)", "/trip", 120000, 1, "Same day", "Covered 10-tonne truck for produce and inputs with experienced driver.", {"Capacity":"10 t","Coverage":"Intra-state"}, [("", 120000), ("— 20 t", 210000), ("— 30 t flatbed", 285000)]),
  ("Pickup Truck Hire (1.5 t, Daily)", "/day", 45000, 1, "Same day", "Hilux-type pickup with driver for farm errands.", {"Capacity":"1.5 t"}, None),
  ("Tipper Truck (Manure / Sand, 20 t)", "/trip", 95000, 1, "Same day", "Tipping truck for bulk manure and construction.", {"Capacity":"20 t"}, None),
  ("Grain Bulk Haulage (per Tonne, Kano → Lagos)", "/tonne", 42000, 10, "3 days", "Bulk grain movement with tarpaulin covers.", {"Min":"10 t"}, None),
 ],
 'Refrigerated Trucks': [
  ("Reefer Truck 10 t (Interstate, per Trip)", "/trip", 650000, 1, "48 hrs", "Insulated 10-tonne refrigerated truck with GPS temperature monitoring.", {"Capacity":"10 t","Temp":"-20 to +10 °C"}, [("", 650000), ("— 3 t van", 280000), ("— 20 t", 1100000)]),
  ("Reefer Container 20 ft (Static Rental, Monthly)", "/month", 450000, 1, "5 days", "On-site refrigerated container with generator option.", {"Size":"20 ft"}, None),
  ("Refrigerated Truck Sales (3 t, New)", "", 38000000, 1, "45 days", "New 3-tonne reefer truck with Thermo King-type unit.", {"Capacity":"3 t"}, None),
 ],
 'Livestock Trucks': [
  ("Livestock Truck — Cattle (30 Head, Kano → Lagos)", "/trip", 950000, 1, "3 days", "Ventilated cattle truck with ramps, water stops and licensed handler.", {"Capacity":"30 head","Handler":"Included"}, [("", 950000), ("— goats/sheep (150 head)", 750000)]),
  ("Poultry Transport Van (Crates, Intra-state)", "/trip", 65000, 1, "Same day", "Crated live-bird transport with ventilation.", {"Crates":"120"}, None),
  ("Day-Old Chick Delivery (Climate-controlled)", "/box", 1500, 10, "24 hrs", "Chick box transport in air-conditioned vans nationwide.", {"Box":"100 chicks"}, None),
  ("Live Fish Transport Tank Truck (2,000 L)", "/trip", 85000, 1, "Same day", "Aerated tank truck for fingerlings and table fish.", {"Volume":"2,000 L"}, None),
 ],
 'Tanker Services': [
  ("Water Tanker Supply (10,000 L)", "/trip", 45000, 1, "Same day", "Clean borehole water delivery for farms and nurseries.", {"Volume":"10,000 L"}, [("", 45000), ("— 20,000 L", 80000)]),
  ("Milk Tanker Collection (Stainless, 5,000 L)", "/trip", 120000, 1, "By schedule", "Insulated milk tanker route collection.", {"Volume":"5,000 L"}, None),
  ("Palm Oil Tanker (33,000 L)", "/trip", 650000, 1, "3 days", "Food-grade tanker for bulk vegetable oil.", {"Volume":"33,000 L"}, None),
  ("Diesel Delivery to Farm (per Litre)", "/L", 1250, 500, "24 hrs", "Metered diesel delivery for generators and tractors.", {"Min":"500 L"}, None),
 ],
 'Machinery Transport': [
  ("Low-Bed Trailer (Tractor / Combine Transport)", "/trip", 450000, 1, "3 days", "Low-loader with ramps and escort for heavy machinery.", {"Capacity":"40 t"}, None),
  ("Tractor Relocation (Intra-state)", "/trip", 150000, 1, "2 days", "Flatbed transport of tractors and implements.", {"Capacity":"1 tractor + implements"}, None),
  ("Crane & Equipment Off-loading", "/hour", 65000, 1, "By schedule", "Mobile crane for silo and machinery installation.", {"Capacity":"25 t"}, None),
 ],
 'Vehicle Rental': [
  ("Tractor & Trailer Rental (Daily)", "/day", 85000, 1, "Same day", "Tractor with 5-tonne farm trailer and operator.", {"Trailer":"5 t"}, None),
  ("Farm Pickup Rental (Weekly)", "/week", 250000, 1, "Same day", "Double-cab 4×4 pickup, self-drive.", {"Type":"4×4 double cab"}, None),
  ("Cargo Tricycle Rental (Monthly)", "/month", 120000, 1, "2 days", "Keke cargo for cooperatives and farm gate collection.", {"Max":"300 kg"}, None),
  ("Mini-Bus Hire for Farm Workers (Daily)", "/day", 55000, 1, "Same day", "18-seater bus for labour transport.", {"Seats":"18"}, None),
 ],
},
'advisory': {
 'Agronomy Consulting': [
  ("Agronomist Farm Visit & Crop Plan", "/visit", 60000, 1, "By schedule", "Certified agronomist visits your farm, assesses soil and crops, and delivers a season plan with input schedule.", {"Duration":"Half day","Report":"Written plan"}, [("", 60000), ("— seasonal retainer (6 visits)", 300000)]),
  ("Greenhouse Crop Management (Monthly)", "/month", 120000, 1, "Monthly", "Weekly visits, fertigation recipes and pest scouting for tunnel farms.", {"Visits":"4 / month"}, None),
  ("Orchard Establishment Consulting (Cashew / Mango / Oil Palm)", "/project", 250000, 1, "14 days", "Site selection, variety choice, layout and 3-year management plan.", {"Deliverable":"Plan + budget"}, None),
  ("Remote Agronomy Support (WhatsApp, Annual)", "/year", 45000, 1, "Instant", "Photo-based diagnosis and advice within 24 hours.", {"Response":"≤ 24 hrs"}, None),
 ],
 'Farm Business Plans': [
  ("Bankable Farm Business Plan", "/plan", 150000, 1, "10 days", "Investor- and bank-ready plan with financial model, cash-flow and sensitivity analysis.", {"Pages":"30–40","Model":"Excel"}, [("", 150000), ("— feasibility study", 350000)]),
  ("Cooperative Registration & Setup", "/coop", 120000, 1, "21 days", "CAC/state registration, bylaws and governance training.", {"Members":"Any"}, None),
  ("Farm Valuation & Due Diligence", "/farm", 250000, 1, "10 days", "Asset and enterprise valuation for sale or investment.", {"Report":"Certified"}, None),
  ("Grant & Tender Proposal Writing", "/proposal", 95000, 1, "7 days", "Proposals for CBN, BOA, IFAD and donor programmes.", {"Success support":"Yes"}, None),
 ],
 'Crop Insurance': [
  ("Crop Insurance — Maize / Rice (per Hectare per Season)", "/ha", 12500, 1, "3 days", "Area-yield index cover against drought, flood and pests through NAIC-licensed underwriters.", {"Cover":"Up to ₦350,000/ha","Perils":"Drought, flood, pest"}, None),
  ("Poultry Insurance (per 1,000 Birds per Cycle)", "/1000", 28000, 1, "3 days", "Mortality cover for disease outbreaks and fire.", {"Cover":"Up to ₦3.5 m"}, None),
  ("Livestock Insurance (Cattle, per Head per Year)", "/head", 18000, 1, "3 days", "Death, theft and disease cover with vet certificate.", {"Cover":"Up to ₦600,000"}, None),
  ("Farm Asset & Equipment Insurance", "/policy", 45000, 1, "5 days", "Fire, theft and breakdown cover for tractors and buildings.", {"Premium":"From 1.5 %"}, None),
 ],
 'Farm Loans': [
  ("Input Financing — Seed & Fertilizer Package (per Ha)", "/ha", 185000, 1, "7 days", "Inputs delivered on credit, repaid at harvest through our off-take partners.", {"Repayment":"At harvest","Interest":"9 % flat"}, None),
  ("Equipment Lease-to-Own (Tractor, Monthly)", "/month", 850000, 1, "14 days", "36-month lease with maintenance included.", {"Term":"36 months"}, None),
  ("Loan Application Support (CBN / BOA / NIRSAL)", "/application", 65000, 1, "10 days", "Document preparation and follow-up for agricultural credit schemes.", {"Schemes":"ACGSF, AADS, BOA"}, None),
  ("Cooperative Micro-Loan Facilitation", "/group", 45000, 1, "14 days", "Group lending setup with partner microfinance banks.", {"Members":"10–30"}, None),
 ],
 'Training Courses': [
  ("Commercial Poultry Farming Course (3 days)", "/person", 55000, 1, "Monthly", "Brooding, feeding, biosecurity, records and marketing on a working farm.", {"Duration":"3 days","Certificate":"Yes"}, [("", 55000), ("— catfish farming", 50000), ("— greenhouse vegetables", 65000), ("— pig farming", 45000)]),
  ("Tractor Operator Training (5 days)", "/person", 85000, 1, "Monthly", "Safe operation, implements and maintenance.", {"Duration":"5 days"}, None),
  ("Agribusiness Bootcamp for Youth (2 weeks)", "/person", 120000, 1, "Quarterly", "From farm plan to market with mentorship.", {"Duration":"2 weeks"}, None),
  ("Beekeeping Workshop (1 day)", "/person", 25000, 1, "Monthly", "Hands-on hive management and harvest.", {"Duration":"1 day"}, None),
  ("Online Course — Farm Records & Finance", "/person", 15000, 1, "Instant", "Self-paced video course with templates.", {"Access":"12 months"}, None),
 ],
 'Soil Testing': [
  ("Soil Test — Standard (pH, NPK, OM, Texture)", "/sample", 18000, 1, "5 days", "Laboratory analysis with fertilizer recommendation for your target crop.", {"Parameters":"8","Turnaround":"5 days"}, [("", 18000), ("— complete (micronutrients)", 32000)]),
  ("Farm Soil Mapping (per 10 ha)", "/10ha", 120000, 1, "10 days", "Grid sampling and nutrient maps for variable-rate application.", {"Grid":"1 ha"}, None),
  ("Irrigation Water Analysis", "/sample", 15000, 1, "5 days", "EC, SAR, pH and contaminants.", {"Parameters":"10"}, None),
  ("Plant Tissue Analysis", "/sample", 22000, 1, "5 days", "Leaf nutrient status for oil palm, cocoa and vegetables.", {"Elements":"12"}, None),
 ],
},
'services': {
 'Land Clearing': [
  ("Land Clearing & Stumping (per Hectare)", "/ha", 185000, 2, "By schedule", "Bulldozer clearing, de-stumping and windrowing for new farmland.", {"Equipment":"D6 bulldozer","Min":"2 ha"}, [("", 185000), ("— light bush (slashing)", 65000)]),
  ("Excavator Hire (Daily)", "/day", 350000, 1, "3 days", "20-tonne excavator with operator for ponds, drains and dams.", {"Class":"20 t"}, None),
  ("Fish Pond Excavation (Earthen, 20 × 30 m)", "/pond", 450000, 1, "7 days", "Earthen pond digging with inlet/outlet structures.", {"Size":"20 × 30 m"}, None),
  ("Farm Road Grading (per km)", "/km", 650000, 1, "7 days", "Grader and compactor for access roads.", {"Width":"6 m"}, None),
 ],
 'Farm Labour': [
  ("Farm Workers — Planting & Weeding (per Worker-Day)", "/worker-day", 4500, 5, "24 hrs", "Vetted and supervised farm hands for planting, weeding and harvesting.", {"Min":"5 workers","Supervisor":"Included"}, None),
  ("Poultry Attendants (Monthly, Live-in)", "/month", 65000, 1, "7 days", "Trained poultry attendants with references.", {"Contract":"Monthly"}, None),
  ("Farm Manager Placement", "/placement", 150000, 1, "14 days", "Recruitment of qualified farm managers (HND/BSc Agric).", {"Guarantee":"3 months"}, None),
  ("Seasonal Harvest Crew (20 Workers, Daily)", "/day", 85000, 1, "3 days", "Organised crew with transport for cassava, maize and vegetables.", {"Workers":"20"}, None),
 ],
 'Harvesting Services': [
  ("Cassava Harvesting (Mechanised, per Ha)", "/ha", 95000, 2, "By schedule", "Tractor-drawn cassava lifter with crew, roots heaped for loading.", {"Equipment":"Cassava lifter"}, None),
  ("Rice Combine Harvesting (per Ha)", "/ha", 65000, 5, "By schedule", "Track combine harvesting and bagging.", {"Min":"5 ha"}, None),
  ("Maize Harvest & Shelling (per Ha)", "/ha", 55000, 2, "By schedule", "Manual harvest with mobile sheller.", {"Output":"Bagged grain"}, None),
  ("Oil Palm Harvesting (per Tonne FFB)", "/tonne", 12000, 5, "By schedule", "Trained harvesters with Malaysian knives and evacuation.", {"Min":"5 t"}, None),
 ],
 'Tractor Hire': [
  ("Ploughing Service (per Hectare)", "/ha", 35000, 1, "By schedule", "Disc ploughing with 75 HP tractor, fuel and operator included.", {"Tractor":"75 HP","Fuel":"Included"}, [("", 35000), ("— harrowing", 28000), ("— ridging", 30000), ("— plough + harrow + ridge package", 85000)]),
  ("Rotavating (per Hectare)", "/ha", 42000, 1, "By schedule", "Fine seedbed preparation for vegetables.", {"Implement":"Rotavator"}, None),
  ("Boom Spraying (per Hectare)", "/ha", 12000, 5, "By schedule", "Tractor boom spraying of herbicides and fertilizer.", {"Boom":"12 m"}, None),
  ("Planter Hire with Tractor (per Hectare)", "/ha", 32000, 2, "By schedule", "Precision planting of maize and soybean.", {"Rows":"4"}, None),
 ],
 'Forestry': [
  ("Teak Seedlings (Improved Clone, 1,000)", "/1000", 350000, 1, "5 days", "Tissue-culture teak clones for plantations.", {"Count":"1,000"}, None),
  ("Gmelina Timber Logs (per Tonne)", "/tonne", 45000, 5, "5 days", "Plantation gmelina logs for construction and pulp.", {"Length":"4 m"}, None),
  ("Bamboo Poles (100 pcs, 6 m)", "/pack", 85000, 1, "5 days", "Treated bamboo for structures and greenhouse frames.", {"Count":"100"}, None),
  ("Charcoal (Hardwood, 50 kg Bag)", "/bag", 12000, 10, "3 days", "Sustainably sourced lump charcoal.", {"Bag":"50 kg"}, None),
  ("Tree Planting & Afforestation Service (per Ha)", "/ha", 250000, 1, "By schedule", "Seedlings, planting and 12-month maintenance.", {"Density":"1,100 trees/ha"}, None),
 ],
 'Farm Land Lease': [
  ("Farmland Lease — Ogun (per Hectare per Year)", "/ha-year", 60000, 5, "14 days", "Surveyed, accessible farmland with water source; documentation and community agreements handled.", {"Min":"5 ha","Water":"River / borehole"}, [("", 60000), ("— Kwara", 40000), ("— Nasarawa", 35000), ("— Oyo", 50000)]),
  ("Farmland for Sale — Epe, Lagos (per Acre)", "/acre", 4500000, 1, "30 days", "Titled farmland 45 minutes from Lekki.", {"Title":"C of O"}, None),
  ("Irrigated Land Lease — Kano (per Ha per Season)", "/ha-season", 85000, 2, "14 days", "Fadama land with canal irrigation for dry-season rice and vegetables.", {"Irrigation":"Canal"}, None),
  ("Land Survey & Title Processing", "/plot", 250000, 1, "60 days", "Survey plan, deed of assignment and registration.", {"Deliverable":"Registered title"}, None),
 ],
},
}
